#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xcee37b39, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0x6c118537, __VMLINUX_SYMBOL_STR(target_unregister_template) },
	{ 0x9176a200, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0x758a8717, __VMLINUX_SYMBOL_STR(target_register_template) },
	{ 0x74b0ed2, __VMLINUX_SYMBOL_STR(target_execute_cmd) },
	{ 0x6316a30d, __VMLINUX_SYMBOL_STR(ib_destroy_cq) },
	{ 0x78f02bdf, __VMLINUX_SYMBOL_STR(ib_send_cm_rej) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x87a04cd1, __VMLINUX_SYMBOL_STR(ib_send_cm_rep) },
	{ 0x9f4fd552, __VMLINUX_SYMBOL_STR(target_alloc_session) },
	{ 0xfd60e15a, __VMLINUX_SYMBOL_STR(ib_create_qp) },
	{ 0xf1d07104, __VMLINUX_SYMBOL_STR(ib_alloc_cq) },
	{ 0xe601bad3, __VMLINUX_SYMBOL_STR(ib_free_recv_mad) },
	{ 0xb678374d, __VMLINUX_SYMBOL_STR(ib_post_send_mad) },
	{ 0xc65c1fb6, __VMLINUX_SYMBOL_STR(ib_create_send_mad) },
	{ 0xe9d8938c, __VMLINUX_SYMBOL_STR(ib_create_ah_from_wc) },
	{ 0xc54e9a8c, __VMLINUX_SYMBOL_STR(ib_cm_init_qp_attr) },
	{ 0xb806af13, __VMLINUX_SYMBOL_STR(ib_cm_notify) },
	{ 0x5860c9b4, __VMLINUX_SYMBOL_STR(transport_send_check_condition_and_sense) },
	{ 0xe32b84f9, __VMLINUX_SYMBOL_STR(target_submit_tmr) },
	{ 0xa9047342, __VMLINUX_SYMBOL_STR(target_submit_cmd_map_sgls) },
	{ 0x9402a6a5, __VMLINUX_SYMBOL_STR(scsilun_to_int) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x8ea288b0, __VMLINUX_SYMBOL_STR(ib_unregister_mad_agent) },
	{ 0x2a565a25, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0x97091d4c, __VMLINUX_SYMBOL_STR(ib_send_cm_drep) },
	{ 0xb1c80c1c, __VMLINUX_SYMBOL_STR(ib_send_cm_dreq) },
	{ 0xf7202784, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0x7f1ac199, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x89f5a825, __VMLINUX_SYMBOL_STR(ib_destroy_srq) },
	{ 0xa8436fab, __VMLINUX_SYMBOL_STR(ib_unregister_event_handler) },
	{ 0x7152ead5, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0x8b3e8b39, __VMLINUX_SYMBOL_STR(ib_register_event_handler) },
	{ 0x38c8a074, __VMLINUX_SYMBOL_STR(ib_cm_listen) },
	{ 0x711cf8ec, __VMLINUX_SYMBOL_STR(ib_create_cm_id) },
	{ 0x9f7ddccf, __VMLINUX_SYMBOL_STR(ib_create_srq) },
	{ 0x7512ed9, __VMLINUX_SYMBOL_STR(__ib_alloc_pd) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6b9dcae8, __VMLINUX_SYMBOL_STR(transport_check_aborted_status) },
	{ 0x4abf51d5, __VMLINUX_SYMBOL_STR(rdma_rw_ctx_wrs) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x21907cfa, __VMLINUX_SYMBOL_STR(ib_free_cq) },
	{ 0x89ed80d1, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x8249aa3c, __VMLINUX_SYMBOL_STR(ib_destroy_cm_id) },
	{ 0x6e8896ab, __VMLINUX_SYMBOL_STR(transport_deregister_session) },
	{ 0x273aec30, __VMLINUX_SYMBOL_STR(transport_deregister_session_configfs) },
	{ 0xd222ed35, __VMLINUX_SYMBOL_STR(target_wait_for_sess_cmds) },
	{ 0x2b226525, __VMLINUX_SYMBOL_STR(target_sess_cmd_list_set_waiting) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xddf5ae1f, __VMLINUX_SYMBOL_STR(transport_generic_request_failure) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x6c21d876, __VMLINUX_SYMBOL_STR(transport_generic_free_cmd) },
	{ 0x3f5b916e, __VMLINUX_SYMBOL_STR(target_put_sess_cmd) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3ab9364d, __VMLINUX_SYMBOL_STR(core_tpg_register) },
	{ 0x971af21b, __VMLINUX_SYMBOL_STR(core_tpg_deregister) },
	{ 0x5377e556, __VMLINUX_SYMBOL_STR(hex2bin) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x96b29254, __VMLINUX_SYMBOL_STR(strncasecmp) },
	{ 0x4ca9669f, __VMLINUX_SYMBOL_STR(scnprintf) },
	{ 0x3c80c06c, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0xe2c423a8, __VMLINUX_SYMBOL_STR(ib_free_send_mad) },
	{ 0xab1f8032, __VMLINUX_SYMBOL_STR(ib_destroy_ah) },
	{ 0x2d772cc6, __VMLINUX_SYMBOL_STR(ib_register_mad_agent) },
	{ 0xb7e847f6, __VMLINUX_SYMBOL_STR(ib_query_gid) },
	{ 0x7be1a1af, __VMLINUX_SYMBOL_STR(ib_query_port) },
	{ 0x183e2b5f, __VMLINUX_SYMBOL_STR(ib_modify_port) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x5d55881, __VMLINUX_SYMBOL_STR(target_free_sgl) },
	{ 0x1ed223bb, __VMLINUX_SYMBOL_STR(rdma_rw_ctx_destroy) },
	{ 0xb5dbd64e, __VMLINUX_SYMBOL_STR(rdma_rw_ctx_init) },
	{ 0xae042b07, __VMLINUX_SYMBOL_STR(target_alloc_sgl) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x8efb1ee3, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xe0d33853, __VMLINUX_SYMBOL_STR(ib_get_client_data) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_core,target_core_mod,ib_cm,scsi_mod";

