#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x1f9ce75e, __VMLINUX_SYMBOL_STR(reset_shadow_zero_bits_mask) },
	{ 0x36e3c4d4, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xac9ce195, __VMLINUX_SYMBOL_STR(kvm_async_pf_task_wait) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x73d1686, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x2c2f5a09, __VMLINUX_SYMBOL_STR(x86_family) },
	{ 0x74c08941, __VMLINUX_SYMBOL_STR(kvm_async_pf_task_wake) },
	{ 0x2a5d7644, __VMLINUX_SYMBOL_STR(kvm_mmu_load) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xfe5233bc, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xd218de77, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x44046cb1, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xdb5a7bb4, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0xfba4c402, __VMLINUX_SYMBOL_STR(kvm_intr_is_single_vcpu) },
	{ 0x30930daa, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x1aacdb24, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0x371f0676, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x80acdda4, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0xece2910d, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0xa4d57013, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0x851fbe0b, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0xc7623eee, __VMLINUX_SYMBOL_STR(kvm_get_rflags) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0x6feb6f2c, __VMLINUX_SYMBOL_STR(kvm_vcpu_wake_up) },
	{ 0x10f8901a, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xf32772f7, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0x5b5cd5c9, __VMLINUX_SYMBOL_STR(kvm_cpuid) },
	{ 0x92cf641a, __VMLINUX_SYMBOL_STR(kvm_mmu_unload) },
	{ 0x9a6f8aa8, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0x3422a941, __VMLINUX_SYMBOL_STR(__tracepoint_read_msr) },
	{ 0x8efb1ee3, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xece458c0, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0x4c1c5b, __VMLINUX_SYMBOL_STR(do_trace_write_msr) },
	{ 0xa50b6b56, __VMLINUX_SYMBOL_STR(ex_handler_clear_fs) },
	{ 0xa06831f8, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x21564cf4, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intercepts) },
	{ 0x9e7cb508, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0x80be3ad, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_invlpga) },
	{ 0x12113a0b, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0x381d4c7d, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x5a5b53ad, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_avic_unaccelerated_access) },
	{ 0x6feb9010, __VMLINUX_SYMBOL_STR(kvm_get_cs_db_l_bits) },
	{ 0x2d1b7746, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x3b1c0f12, __VMLINUX_SYMBOL_STR(x86_set_memory_region) },
	{ 0x8e05f077, __VMLINUX_SYMBOL_STR(kvm_mmu_unprotect_page_virt) },
	{ 0x79611469, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest_page) },
	{ 0x59c1d110, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0x35b9450d, __VMLINUX_SYMBOL_STR(__tracepoint_write_msr) },
	{ 0xffd0d748, __VMLINUX_SYMBOL_STR(load_pdptrs) },
	{ 0xc1adc2cb, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_skinit) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x73adacc7, __VMLINUX_SYMBOL_STR(kvm_write_tsc) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x5fdfa2c1, __VMLINUX_SYMBOL_STR(amd_pmu_enable_virt) },
	{ 0x70f9719, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xe561b9e1, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0x479c3c86, __VMLINUX_SYMBOL_STR(find_next_zero_bit) },
	{ 0xb2ffcbb7, __VMLINUX_SYMBOL_STR(kvm_set_msi_irq) },
	{ 0xc3be53ca, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0x3e1f72e0, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0x93c95f13, __VMLINUX_SYMBOL_STR(kvm_is_linear_rip) },
	{ 0x682f8e9d, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x6636c3c9, __VMLINUX_SYMBOL_STR(irq_set_vcpu_affinity) },
	{ 0x75ab5d7f, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0xf0113640, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x41039ebe, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x2ff59594, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0x7a9b30bd, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0x36a7f48a, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0x37f542f6, __VMLINUX_SYMBOL_STR(kvm_scale_tsc) },
	{ 0xb1cc6be5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0x2e2df7f4, __VMLINUX_SYMBOL_STR(irq_remapping_cap) },
	{ 0x73ae496a, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_page_fault) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0xd7326498, __VMLINUX_SYMBOL_STR(kvm_set_rflags) },
	{ 0x33e9ee0d, __VMLINUX_SYMBOL_STR(kvm_lapic_reg_write) },
	{ 0xd4adf8b, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intr_vmexit) },
	{ 0x82a27d45, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xcde03c4b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xf41e94f5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pi_irte_update) },
	{ 0x28f58fd8, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0x6f75e3ea, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x2d2d3b1d, __VMLINUX_SYMBOL_STR(cpu_tlbstate) },
	{ 0xc6234241, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xabf11d53, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xcabdd581, __VMLINUX_SYMBOL_STR(kvm_init_shadow_mmu) },
	{ 0x775a6ef5, __VMLINUX_SYMBOL_STR(kvm_read_and_reset_pf_reason) },
	{ 0x3d9ee9f0, __VMLINUX_SYMBOL_STR(clear_page) },
	{ 0xfa31d89d, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0x621820cb, __VMLINUX_SYMBOL_STR(amd_iommu_register_ga_log_notifier) },
	{ 0xfde3eb7b, __VMLINUX_SYMBOL_STR(pv_cpu_ops) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0x3931935c, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0xbdffca14, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0xc73a8771, __VMLINUX_SYMBOL_STR(do_trace_read_msr) },
	{ 0x72742a95, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x58dddca6, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x77f1dde8, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xed433664, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x2474c277, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0x3a0975d, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x1226bdb6, __VMLINUX_SYMBOL_STR(ex_handler_default) },
	{ 0x7ff1ca84, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmrun) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xf6656a3f, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0x6340434e, __VMLINUX_SYMBOL_STR(x86_model) },
	{ 0xc5137552, __VMLINUX_SYMBOL_STR(x86_bios_cpu_apicid) },
	{ 0x16abbdb0, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa362e027, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x8db702ae, __VMLINUX_SYMBOL_STR(pv_mmu_ops) },
	{ 0x4b9a6d8, __VMLINUX_SYMBOL_STR(__cpu_present_mask) },
	{ 0x3f8f9119, __VMLINUX_SYMBOL_STR(kvm_no_apic_vcpu) },
	{ 0xa38f21b9, __VMLINUX_SYMBOL_STR(amd_iommu_update_ga) },
	{ 0x4b61488d, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0xf8f4642c, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0xa930fa6c, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_avic_incomplete_ipi) },
	{ 0xe102bb9f, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x78891bef, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0xb2ad45fb, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x18582826, __VMLINUX_SYMBOL_STR(amd_pmu_disable_virt) },
	{ 0x2b9b074d, __VMLINUX_SYMBOL_STR(kvm_apic_match_dest) },
	{ 0x37c95171, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
	{ 0x4b8412c, __VMLINUX_SYMBOL_STR(kvm_arch_has_assigned_device) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("cpu:type:x86,ven*fam*mod*:feature:*00C2*");
