#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x36e3c4d4, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x3d2a5ba8, __VMLINUX_SYMBOL_STR(kvm_lapic_hv_timer_in_use) },
	{ 0x23fd0565, __VMLINUX_SYMBOL_STR(kvm_apic_write_nodecode) },
	{ 0xa7d9c68f, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mask_ptes) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x73d1686, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x62dc7c4d, __VMLINUX_SYMBOL_STR(kvm_vcpu_write_guest) },
	{ 0x7991fd8d, __VMLINUX_SYMBOL_STR(crash_vmclear_loaded_vmcss) },
	{ 0x30f7f493, __VMLINUX_SYMBOL_STR(kvm_cpu_get_interrupt) },
	{ 0xbb0b686a, __VMLINUX_SYMBOL_STR(kvm_mmu_sync_roots) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xfe5233bc, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xf4e82e5f, __VMLINUX_SYMBOL_STR(kvm_inject_page_fault) },
	{ 0xd218de77, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x64020e10, __VMLINUX_SYMBOL_STR(kvm_set_shared_msr) },
	{ 0x44046cb1, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xdb5a7bb4, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0xfba4c402, __VMLINUX_SYMBOL_STR(kvm_intr_is_single_vcpu) },
	{ 0x30930daa, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x1aacdb24, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0x240687c8, __VMLINUX_SYMBOL_STR(kvm_inject_realmode_interrupt) },
	{ 0x830aa37f, __VMLINUX_SYMBOL_STR(kvm_vcpu_kick) },
	{ 0x371f0676, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x7f9b3788, __VMLINUX_SYMBOL_STR(node_data) },
	{ 0xad7a37a7, __VMLINUX_SYMBOL_STR(kvm_apic_set_eoi_accelerated) },
	{ 0x80acdda4, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0xece2910d, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0xa4d57013, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0xe418fde4, __VMLINUX_SYMBOL_STR(hrtimer_cancel) },
	{ 0x851fbe0b, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0x10f8901a, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0x7d9c2402, __VMLINUX_SYMBOL_STR(__hrtimer_get_remaining) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xf32772f7, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0x92cf641a, __VMLINUX_SYMBOL_STR(kvm_mmu_unload) },
	{ 0x9a6f8aa8, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x8efb1ee3, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xece458c0, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0xa1374974, __VMLINUX_SYMBOL_STR(put_zone_device_page) },
	{ 0x60082f54, __VMLINUX_SYMBOL_STR(kvm_mtrr_get_guest_memory_type) },
	{ 0xbcb8c54, __VMLINUX_SYMBOL_STR(kvm_vcpu_reload_apic_access_page) },
	{ 0xa50b6b56, __VMLINUX_SYMBOL_STR(ex_handler_clear_fs) },
	{ 0x3e3bcce9, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xa06831f8, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x9e7cb508, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0x12113a0b, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0x791b7a61, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x381d4c7d, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x9764541a, __VMLINUX_SYMBOL_STR(__x86_set_memory_region) },
	{ 0xc0667c25, __VMLINUX_SYMBOL_STR(kvm_release_page_clean) },
	{ 0x2d1b7746, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0xa7b1507, __VMLINUX_SYMBOL_STR(hrtimer_start_range_ns) },
	{ 0x3b1c0f12, __VMLINUX_SYMBOL_STR(x86_set_memory_region) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x8e05f077, __VMLINUX_SYMBOL_STR(kvm_mmu_unprotect_page_virt) },
	{ 0x96dbe382, __VMLINUX_SYMBOL_STR(kvm_mpx_supported) },
	{ 0x8a476878, __VMLINUX_SYMBOL_STR(handle_mmio_page_fault) },
	{ 0x59c1d110, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0xc780592e, __VMLINUX_SYMBOL_STR(kvm_get_msr) },
	{ 0x73adacc7, __VMLINUX_SYMBOL_STR(kvm_write_tsc) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x75bc549a, __VMLINUX_SYMBOL_STR(x86_cpu_to_apicid) },
	{ 0x5dbea1b5, __VMLINUX_SYMBOL_STR(kvm_get_linear_rip) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x70f9719, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xe561b9e1, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0xb2ffcbb7, __VMLINUX_SYMBOL_STR(kvm_set_msi_irq) },
	{ 0xc3be53ca, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0x3e1f72e0, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0x8f28d7ac, __VMLINUX_SYMBOL_STR(vcpu_load) },
	{ 0x682f8e9d, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x6636c3c9, __VMLINUX_SYMBOL_STR(irq_set_vcpu_affinity) },
	{ 0x75ab5d7f, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0xf0113640, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x3f24479e, __VMLINUX_SYMBOL_STR(kvm_lapic_switch_to_sw_timer) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3b91db5b, __VMLINUX_SYMBOL_STR(intel_pt_handle_vmx) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x41039ebe, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x2ff59594, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0xf37d7e4, __VMLINUX_SYMBOL_STR(kvm_apic_update_irr) },
	{ 0x7a9b30bd, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0xb6a68816, __VMLINUX_SYMBOL_STR(find_last_bit) },
	{ 0x36a7f48a, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0x37f542f6, __VMLINUX_SYMBOL_STR(kvm_scale_tsc) },
	{ 0xe7216340, __VMLINUX_SYMBOL_STR(cpu_bit_bitmap) },
	{ 0x6091797f, __VMLINUX_SYMBOL_STR(synchronize_rcu) },
	{ 0xc56d75ce, __VMLINUX_SYMBOL_STR(__kvm_apic_update_irr) },
	{ 0x8d65877, __VMLINUX_SYMBOL_STR(kvm_cpu_has_interrupt) },
	{ 0xb1cc6be5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0xe8f8f626, __VMLINUX_SYMBOL_STR(kvm_read_l1_tsc) },
	{ 0xdd05b028, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_set_dirty) },
	{ 0x2e2df7f4, __VMLINUX_SYMBOL_STR(irq_remapping_cap) },
	{ 0x73ae496a, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_page_fault) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0x34d01a87, __VMLINUX_SYMBOL_STR(kvm_mce_cap_supported) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0x9b646942, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_leaf_clear_dirty) },
	{ 0x7b8ff104, __VMLINUX_SYMBOL_STR(kvm_valid_efer) },
	{ 0x82a27d45, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xcde03c4b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xc287d96a, __VMLINUX_SYMBOL_STR(kvm_set_posted_intr_wakeup_handler) },
	{ 0xc3b80761, __VMLINUX_SYMBOL_STR(kvm_write_guest_page) },
	{ 0x618911fc, __VMLINUX_SYMBOL_STR(numa_node) },
	{ 0xf41e94f5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pi_irte_update) },
	{ 0x28f58fd8, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0x6f75e3ea, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x2d2d3b1d, __VMLINUX_SYMBOL_STR(cpu_tlbstate) },
	{ 0x93fca811, __VMLINUX_SYMBOL_STR(__get_free_pages) },
	{ 0xc6234241, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0x4d9bd549, __VMLINUX_SYMBOL_STR(kvm_lapic_switch_to_hv_timer) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xabf11d53, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x8ae6a917, __VMLINUX_SYMBOL_STR(kvm_lapic_set_eoi) },
	{ 0x5657cc09, __VMLINUX_SYMBOL_STR(kvm_lmsw) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0xfa31d89d, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0xcf0b30d5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pml_full) },
	{ 0xbf8c0a5d, __VMLINUX_SYMBOL_STR(kvm_init_shadow_ept_mmu) },
	{ 0xfde3eb7b, __VMLINUX_SYMBOL_STR(pv_cpu_ops) },
	{ 0x6a67c32b, __VMLINUX_SYMBOL_STR(kvm_require_cpl) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0xd782e438, __VMLINUX_SYMBOL_STR(kvm_mmu_clear_dirty_pt_masked) },
	{ 0xba9ed435, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mmio_spte_mask) },
	{ 0xdc444f6a, __VMLINUX_SYMBOL_STR(kvm_io_bus_write) },
	{ 0xfbd95c91, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_cr) },
	{ 0xf2312a76, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_ple_window) },
	{ 0x3931935c, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0xbdffca14, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x4bbcf486, __VMLINUX_SYMBOL_STR(kvm_read_guest_virt) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0x72742a95, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x58dddca6, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0xb892fb61, __VMLINUX_SYMBOL_STR(kvm_write_guest_virt_system) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x77f1dde8, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xed433664, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x1915af97, __VMLINUX_SYMBOL_STR(kvm_mtrr_valid) },
	{ 0x2474c277, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0x3a0975d, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x9a216313, __VMLINUX_SYMBOL_STR(kvm_define_shared_msr) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0x1226bdb6, __VMLINUX_SYMBOL_STR(ex_handler_default) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xf8f18982, __VMLINUX_SYMBOL_STR(kvm_set_apic_base) },
	{ 0xf6656a3f, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0xd02f4d08, __VMLINUX_SYMBOL_STR(kvm_arch_has_noncoherent_dma) },
	{ 0x16abbdb0, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x1ccd216, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_fast_mmio) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x45b68ec3, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_largepage_remove_write_access) },
	{ 0xa362e027, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x8db702ae, __VMLINUX_SYMBOL_STR(pv_mmu_ops) },
	{ 0x2b87ffe5, __VMLINUX_SYMBOL_STR(reprogram_fixed_counter) },
	{ 0x83ba5fbb, __VMLINUX_SYMBOL_STR(hrtimer_init) },
	{ 0x3f8f9119, __VMLINUX_SYMBOL_STR(kvm_no_apic_vcpu) },
	{ 0xecad3b34, __VMLINUX_SYMBOL_STR(do_machine_check) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xf231d020, __VMLINUX_SYMBOL_STR(gfn_to_page) },
	{ 0x7f7fc3d9, __VMLINUX_SYMBOL_STR(kvm_lapic_expired_hv_timer) },
	{ 0x4b61488d, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0x5b294e32, __VMLINUX_SYMBOL_STR(apic) },
	{ 0xf8f4642c, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0xafaffb, __VMLINUX_SYMBOL_STR(kvm_default_tsc_scaling_ratio) },
	{ 0xe102bb9f, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x78891bef, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0x9716e7a8, __VMLINUX_SYMBOL_STR(reprogram_counter) },
	{ 0x48682db9, __VMLINUX_SYMBOL_STR(perf_guest_get_msrs) },
	{ 0x20de5193, __VMLINUX_SYMBOL_STR(kvm_disable_largepages) },
	{ 0xb2ad45fb, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x877f3cf5, __VMLINUX_SYMBOL_STR(kvm_clear_guest_page) },
	{ 0x32279eac, __VMLINUX_SYMBOL_STR(kvm_vcpu_halt) },
	{ 0x6228c21f, __VMLINUX_SYMBOL_STR(smp_call_function_single) },
	{ 0xce104fcc, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x6268ed10, __VMLINUX_SYMBOL_STR(kvm_vcpu_mark_page_dirty) },
	{ 0x37c95171, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
	{ 0x4b8412c, __VMLINUX_SYMBOL_STR(kvm_arch_has_assigned_device) },
	{ 0xa5ede44e, __VMLINUX_SYMBOL_STR(vcpu_put) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("cpu:type:x86,ven*fam*mod*:feature:*0085*");
