#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x3e6741b2, __VMLINUX_SYMBOL_STR(snd_hdac_power_up) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x402b8281, __VMLINUX_SYMBOL_STR(__request_module) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xb87999e4, __VMLINUX_SYMBOL_STR(snd_hdac_stream_start) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xc2d59bbb, __VMLINUX_SYMBOL_STR(driver_register) },
	{ 0x810849e9, __VMLINUX_SYMBOL_STR(pm_runtime_force_suspend) },
	{ 0xc3d672ca, __VMLINUX_SYMBOL_STR(snd_hdac_refresh_widget_sysfs) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2d62d364, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_cleanup) },
	{ 0x2ed9019d, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0xc120396c, __VMLINUX_SYMBOL_STR(snd_pcm_lib_default_mmap) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x5bed491b, __VMLINUX_SYMBOL_STR(snd_hdac_codec_read) },
	{ 0xa08f28e8, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x53ecf8ff, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_trigger) },
	{ 0x9a8e1877, __VMLINUX_SYMBOL_STR(snd_array_free) },
	{ 0x1c4d6c42, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_step) },
	{ 0xbdb6d803, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x9f96a06b, __VMLINUX_SYMBOL_STR(snd_hdac_stream_reset) },
	{ 0x55a0bd39, __VMLINUX_SYMBOL_STR(snd_hdac_link_power) },
	{ 0x3b8b9795, __VMLINUX_SYMBOL_STR(snd_device_free) },
	{ 0x52232134, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync_trigger) },
	{ 0xbe7dd7dc, __VMLINUX_SYMBOL_STR(snd_array_new) },
	{ 0xe3bde5bb, __VMLINUX_SYMBOL_STR(snd_info_create_card_entry) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xaf2c529, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x9229299e, __VMLINUX_SYMBOL_STR(snd_pci_quirk_lookup) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x25f39632, __VMLINUX_SYMBOL_STR(pm_runtime_force_resume) },
	{ 0xc06661e4, __VMLINUX_SYMBOL_STR(snd_hdac_bus_handle_stream_irq) },
	{ 0x3dc8879e, __VMLINUX_SYMBOL_STR(snd_device_disconnect) },
	{ 0x20b1b7aa, __VMLINUX_SYMBOL_STR(snd_hdac_get_sub_nodes) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x7d93cca2, __VMLINUX_SYMBOL_STR(snd_hdac_stream_set_params) },
	{ 0xa9dcaab0, __VMLINUX_SYMBOL_STR(snd_hdac_stream_setup) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x2a1314cc, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0xd4825f5d, __VMLINUX_SYMBOL_STR(pm_runtime_allow) },
	{ 0xc0998f21, __VMLINUX_SYMBOL_STR(snd_hdac_device_exit) },
	{ 0xe7dfd697, __VMLINUX_SYMBOL_STR(pm_runtime_forbid) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0xec4df693, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_integer) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xb69d457, __VMLINUX_SYMBOL_STR(snd_hda_bus_type) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x7d6f81a1, __VMLINUX_SYMBOL_STR(_snd_ctl_add_slave) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x57caaafe, __VMLINUX_SYMBOL_STR(snd_pcm_suspend_all) },
	{ 0xd1ce0815, __VMLINUX_SYMBOL_STR(snd_hdac_check_power_state) },
	{ 0xdc8598e3, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_exit) },
	{ 0x3c80c06c, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0xd64b2aec, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0x3dd12a0b, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x8fe59cef, __VMLINUX_SYMBOL_STR(convert_art_to_tsc) },
	{ 0xeec8156c, __VMLINUX_SYMBOL_STR(snd_device_new) },
	{ 0xd84f17e6, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_write_raw) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x2e2b40d2, __VMLINUX_SYMBOL_STR(strncat) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x307ef8b3, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync) },
	{ 0x43d97d3e, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_cmd_io) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0xe0ab8897, __VMLINUX_SYMBOL_STR(snd_pcm_set_ops) },
	{ 0x65ab216, __VMLINUX_SYMBOL_STR(driver_unregister) },
	{ 0xf40e9158, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0x662ba86e, __VMLINUX_SYMBOL_STR(snd_hdac_device_set_chip_name) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xc2c60979, __VMLINUX_SYMBOL_STR(snd_hdac_power_down_pm) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd365eb3a, __VMLINUX_SYMBOL_STR(device_attach) },
	{ 0x7f68019d, __VMLINUX_SYMBOL_STR(snd_hdac_read) },
	{ 0xa4f8299d, __VMLINUX_SYMBOL_STR(snd_hwdep_new) },
	{ 0x628a5db0, __VMLINUX_SYMBOL_STR(snd_jack_new) },
	{ 0x856366e5, __VMLINUX_SYMBOL_STR(snd_hdac_stream_assign) },
	{ 0x5d4a8320, __VMLINUX_SYMBOL_STR(kvasprintf) },
	{ 0xb5815e32, __VMLINUX_SYMBOL_STR(snd_hdac_device_init) },
	{ 0xe05a21af, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0x736b90d1, __VMLINUX_SYMBOL_STR(snd_hdac_device_unregister) },
	{ 0xe3a53f4c, __VMLINUX_SYMBOL_STR(sort) },
	{ 0xb02c435c, __VMLINUX_SYMBOL_STR(snd_hdac_stream_init) },
	{ 0xee6dc507, __VMLINUX_SYMBOL_STR(perf_trace_run_bpf_submit) },
	{ 0x5d12b4e1, __VMLINUX_SYMBOL_STR(snd_hdac_read_parm_uncached) },
	{ 0xad5f0017, __VMLINUX_SYMBOL_STR(perf_trace_buf_alloc) },
	{ 0xdd9a804a, __VMLINUX_SYMBOL_STR(snd_hdac_calc_stream_format) },
	{ 0xaa6cf8e9, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_mono_info) },
	{ 0xaf6ae696, __VMLINUX_SYMBOL_STR(kstrndup) },
	{ 0x7c3a6478, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init) },
	{ 0xc542933a, __VMLINUX_SYMBOL_STR(timecounter_read) },
	{ 0xdd1dbdb, __VMLINUX_SYMBOL_STR(snd_hdac_stream_cleanup) },
	{ 0x81b69e41, __VMLINUX_SYMBOL_STR(snd_ctl_enum_info) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0x3e046816, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x8e5984e1, __VMLINUX_SYMBOL_STR(snd_hdac_stream_stop) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x9a6e8331, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_chip) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xd278061b, __VMLINUX_SYMBOL_STR(snd_ctl_make_virtual_master) },
	{ 0x2f2516f, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_update_raw) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xbe798726, __VMLINUX_SYMBOL_STR(snd_hdac_device_register) },
	{ 0xef9c6ab8, __VMLINUX_SYMBOL_STR(snd_component_add) },
	{ 0x854f23f1, __VMLINUX_SYMBOL_STR(snd_hdac_override_parm) },
	{ 0x3f602ae9, __VMLINUX_SYMBOL_STR(snd_hdac_bus_exec_verb_unlocked) },
	{ 0x4e1b99f, __VMLINUX_SYMBOL_STR(snd_pcm_std_chmaps) },
	{ 0x5cbe052f, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x2e4d11e8, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0x3e05bf46, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x1bed39b3, __VMLINUX_SYMBOL_STR(input_register_device) },
	{ 0xc1ef82d, __VMLINUX_SYMBOL_STR(_snd_hdac_read_parm) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x96b29254, __VMLINUX_SYMBOL_STR(strncasecmp) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x62a46ffe, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_prepare) },
	{ 0xeb59d6a3, __VMLINUX_SYMBOL_STR(snd_ctl_new1) },
	{ 0x8f941070, __VMLINUX_SYMBOL_STR(input_free_device) },
	{ 0x211f68f1, __VMLINUX_SYMBOL_STR(getnstimeofday64) },
	{ 0xdc909ca8, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x2d45137b, __VMLINUX_SYMBOL_STR(snd_hdac_stream_timecounter_init) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x12dd745c, __VMLINUX_SYMBOL_STR(snd_pcm_set_sync) },
	{ 0x123f82f3, __VMLINUX_SYMBOL_STR(getrawmonotonic64) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x926d0b67, __VMLINUX_SYMBOL_STR(snd_ctl_find_id) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3ecd2f5d, __VMLINUX_SYMBOL_STR(snd_ctl_remove) },
	{ 0x1e13f75c, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0xc5baf3c3, __VMLINUX_SYMBOL_STR(snd_ctl_sync_vmaster) },
	{ 0x4dae5252, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0xfc9a1f6a, __VMLINUX_SYMBOL_STR(regcache_mark_dirty) },
	{ 0x4773ba1b, __VMLINUX_SYMBOL_STR(snd_ctl_add_vmaster_hook) },
	{ 0xc20f9b58, __VMLINUX_SYMBOL_STR(snd_hdac_query_supported_pcm) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4835d0a8, __VMLINUX_SYMBOL_STR(input_unregister_device) },
	{ 0x37835914, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0xb2f1ff96, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_chip) },
	{ 0xd0a91bab, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0x5843b589, __VMLINUX_SYMBOL_STR(snd_hdac_codec_modalias) },
	{ 0xb44f953e, __VMLINUX_SYMBOL_STR(get_device_system_crosststamp) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0x50060c55, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_minmax) },
	{ 0xa6e4bbe4, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_init) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x832adf75, __VMLINUX_SYMBOL_STR(snd_hdac_codec_write) },
	{ 0xea7c17a, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0xc6d935da, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xeefe1446, __VMLINUX_SYMBOL_STR(snd_card_register) },
	{ 0x4c509aca, __VMLINUX_SYMBOL_STR(snd_pcm_add_chmap_ctls) },
	{ 0x2c064436, __VMLINUX_SYMBOL_STR(snd_hdac_power_down) },
	{ 0xc6b3dc99, __VMLINUX_SYMBOL_STR(snd_hdac_bus_update_rirb) },
	{ 0x1baab8d, __VMLINUX_SYMBOL_STR(snd_pcm_limit_hw_rates) },
	{ 0x8d32b478, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xf87a6fc, __VMLINUX_SYMBOL_STR(snd_jack_report) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x6ad0b4cb, __VMLINUX_SYMBOL_STR(snd_pcm_new) },
	{ 0x11caddc7, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x64e65978, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_read_raw) },
	{ 0xcfb50808, __VMLINUX_SYMBOL_STR(snd_hdac_is_supported_format) },
	{ 0xccc241a8, __VMLINUX_SYMBOL_STR(snd_ctl_add) },
	{ 0xd56b5f64, __VMLINUX_SYMBOL_STR(ktime_get_ts64) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0xa724a88a, __VMLINUX_SYMBOL_STR(snd_hdac_bus_send_cmd) },
	{ 0xa1c46150, __VMLINUX_SYMBOL_STR(regcache_sync) },
	{ 0x86837599, __VMLINUX_SYMBOL_STR(regcache_cache_only) },
	{ 0x9e7d6bd0, __VMLINUX_SYMBOL_STR(__udelay) },
	{ 0x3f0f863f, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x63381fbc, __VMLINUX_SYMBOL_STR(snd_hdac_power_up_pm) },
	{ 0xce85932d, __VMLINUX_SYMBOL_STR(snd_hdac_get_connections) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x92d6f964, __VMLINUX_SYMBOL_STR(snd_hdac_stream_release) },
	{ 0x1ec9b065, __VMLINUX_SYMBOL_STR(input_allocate_device) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-hda-core,snd-pcm,snd,snd-hwdep";

