#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x5bfac336, __VMLINUX_SYMBOL_STR(pnfs_unregister_layoutdriver) },
	{ 0x2aa90f88, __VMLINUX_SYMBOL_STR(nfs4_schedule_session_recovery) },
	{ 0x36e3c4d4, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x825de13f, __VMLINUX_SYMBOL_STR(pnfs_nfs_generic_sync) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xaf5bf6ef, __VMLINUX_SYMBOL_STR(nfs_debug) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2f1a8ba8, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_connect) },
	{ 0x8136864f, __VMLINUX_SYMBOL_STR(pnfs_generic_clear_request_commit) },
	{ 0x8b931646, __VMLINUX_SYMBOL_STR(nfs_init_cinfo) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0x6eec272c, __VMLINUX_SYMBOL_STR(nfs_initiate_commit) },
	{ 0x765ba0c4, __VMLINUX_SYMBOL_STR(pnfs_error_mark_layout_for_return) },
	{ 0x16d624f, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_put) },
	{ 0x24a6b8f9, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x54bef45, __VMLINUX_SYMBOL_STR(layoutstats_timer) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x643d9ba1, __VMLINUX_SYMBOL_STR(groups_free) },
	{ 0xf68f23ca, __VMLINUX_SYMBOL_STR(nfs4_mark_deviceid_unavailable) },
	{ 0x1093b108, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_commit_ds) },
	{ 0x5c12d50e, __VMLINUX_SYMBOL_STR(nfs4_decode_mp_ds_addr) },
	{ 0xa6a2d526, __VMLINUX_SYMBOL_STR(nfs_initiate_pgio) },
	{ 0xf47d2741, __VMLINUX_SYMBOL_STR(nfs4_set_rw_stateid) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0xe3b17aef, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_pagelist) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0x36bd215a, __VMLINUX_SYMBOL_STR(pnfs_generic_recover_commit_reqs) },
	{ 0x25591d58, __VMLINUX_SYMBOL_STR(nfs41_setup_sequence) },
	{ 0xf0e82b97, __VMLINUX_SYMBOL_STR(nfs4_sequence_done) },
	{ 0x6daf086d, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xa7ef6ffa, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_test) },
	{ 0x9d214b0c, __VMLINUX_SYMBOL_STR(nfs4_schedule_lease_recovery) },
	{ 0xa46387b4, __VMLINUX_SYMBOL_STR(pnfs_update_layout) },
	{ 0xa68390cc, __VMLINUX_SYMBOL_STR(rpc_exit) },
	{ 0xa5d15954, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_cleanup) },
	{ 0xfcdb0745, __VMLINUX_SYMBOL_STR(pnfs_generic_write_commit_done) },
	{ 0x1c56824c, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x7d951cec, __VMLINUX_SYMBOL_STR(pnfs_generic_layout_insert_lseg) },
	{ 0xedabbb2b, __VMLINUX_SYMBOL_STR(xdr_init_decode_pages) },
	{ 0x12099557, __VMLINUX_SYMBOL_STR(rpc_call_start) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0xe2c9026b, __VMLINUX_SYMBOL_STR(nfs40_setup_sequence) },
	{ 0x22d038f1, __VMLINUX_SYMBOL_STR(pnfs_read_resend_pnfs) },
	{ 0x4ec74210, __VMLINUX_SYMBOL_STR(nfs4_find_get_deviceid) },
	{ 0xa04c5492, __VMLINUX_SYMBOL_STR(nfs4_find_or_create_ds_client) },
	{ 0x4b1b8583, __VMLINUX_SYMBOL_STR(rpc_max_payload) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xfaf84800, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_write_mds) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x3ffcdada, __VMLINUX_SYMBOL_STR(pnfs_layout_mark_request_commit) },
	{ 0x972ed11f, __VMLINUX_SYMBOL_STR(pnfs_destroy_layout) },
	{ 0x35ef3a71, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_add) },
	{ 0x519e292, __VMLINUX_SYMBOL_STR(pnfs_layoutcommit_inode) },
	{ 0xf6955e75, __VMLINUX_SYMBOL_STR(pnfs_put_lseg) },
	{ 0x70e6a057, __VMLINUX_SYMBOL_STR(nfs4_put_deviceid_node) },
	{ 0xa3f817e7, __VMLINUX_SYMBOL_STR(pnfs_report_layoutstat) },
	{ 0xed15fb41, __VMLINUX_SYMBOL_STR(nfs4_print_deviceid) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0xa13d99ed, __VMLINUX_SYMBOL_STR(pnfs_set_layoutcommit) },
	{ 0xe93da0df, __VMLINUX_SYMBOL_STR(pnfs_generic_scan_commit_lists) },
	{ 0x69d3558d, __VMLINUX_SYMBOL_STR(pnfs_generic_rw_release) },
	{ 0xcde03c4b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x3ef43921, __VMLINUX_SYMBOL_STR(nfs4_schedule_stateid_recovery) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x1ab26e61, __VMLINUX_SYMBOL_STR(nfs4_test_deviceid_unavailable) },
	{ 0x6085edbd, __VMLINUX_SYMBOL_STR(nfs_map_string_to_numeric) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xf999267e, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_release) },
	{ 0xa1a0d8aa, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0x53efe980, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_readpages) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0x43964221, __VMLINUX_SYMBOL_STR(pnfs_read_done_resend_to_mds) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0x43ac88f3, __VMLINUX_SYMBOL_STR(rpc_restart_call_prepare) },
	{ 0xd8b5e860, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x3e2b0ba6, __VMLINUX_SYMBOL_STR(groups_alloc) },
	{ 0xf8c24dec, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_writepages) },
	{ 0x18c011aa, __VMLINUX_SYMBOL_STR(pnfs_generic_prepare_to_resend_writes) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xd0b5b7dc, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_read) },
	{ 0x351a826f, __VMLINUX_SYMBOL_STR(pnfs_write_done_resend_to_mds) },
	{ 0x37c3c34d, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0x1e588f16, __VMLINUX_SYMBOL_STR(rpc_count_iostats_metrics) },
	{ 0xf3ba48f1, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0xb0480ef3, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_write) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xeefbdfe7, __VMLINUX_SYMBOL_STR(rpc_lookup_generic_cred) },
	{ 0xbf73ac8d, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_read_mds) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xf02baecf, __VMLINUX_SYMBOL_STR(nfs4_init_deviceid_node) },
	{ 0x4a492ac9, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x140a15ea, __VMLINUX_SYMBOL_STR(nfs_remove_bad_delegation) },
	{ 0x52d56a6b, __VMLINUX_SYMBOL_STR(xdr_set_scratch_buffer) },
	{ 0x7614e146, __VMLINUX_SYMBOL_STR(nfs_writeback_update_inode) },
	{ 0x997e459c, __VMLINUX_SYMBOL_STR(pnfs_register_layoutdriver) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=nfsv4,sunrpc,nfs";

