cmd_/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o := gcc -Wp,-MD,/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/.elf.o.d,-MT,/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o -Wall -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-aliasing=3 -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -fomit-frame-pointer -O2 -g -I/home/student/ws_student/kernel/linux-4.9.56/tools/include -I/home/student/ws_student/kernel/linux-4.9.56/tools/arch/x86/include/uapi  -I/home/student/ws_student/kernel/linux-4.9.56/tools/lib -D"BUILD_STR(s)=\#s"   -c -o /home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o elf.c

source_/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o := elf.c

deps_/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o := \
  /usr/include/stdc-predef.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/bits/string.h \
  /usr/include/bits/string2.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/elf.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/list.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include/stdbool.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitsperlong.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/uapi/asm-generic/bitsperlong.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/poison.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/compiler.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/hashtable.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/bitops.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/__ffs.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/fls.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/__fls.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/fls64.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/find.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/hweight.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/const_hweight.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/asm-generic/bitops/atomic.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/hash.h \
  /home/student/ws_student/kernel/linux-4.9.56/tools/include/linux/log2.h \
  warn.h \

/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o: $(deps_/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o)

$(deps_/home/student/ws_student/kernel/linux-4.9.56/tools/objtool/elf.o):
