#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x5d9779d9, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0xf7eb43ae, __VMLINUX_SYMBOL_STR(sg_alloc_table_chained) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x7f1ac199, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x207e208d, __VMLINUX_SYMBOL_STR(ib_drain_qp) },
	{ 0x2ad65f89, __VMLINUX_SYMBOL_STR(blk_mq_tagset_busy_iter) },
	{ 0x48302bd3, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0x426f035c, __VMLINUX_SYMBOL_STR(nvmf_register_transport) },
	{ 0x89ed80d1, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x7cc83b13, __VMLINUX_SYMBOL_STR(nvme_shutdown_ctrl) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x11e74ecb, __VMLINUX_SYMBOL_STR(nvme_set_queue_count) },
	{ 0x8efb1ee3, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xccf2f1ad, __VMLINUX_SYMBOL_STR(nvme_stop_queues) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x3a36bcd9, __VMLINUX_SYMBOL_STR(blk_mq_tag_to_rq) },
	{ 0xb77616a3, __VMLINUX_SYMBOL_STR(nvme_complete_async_event) },
	{ 0xd99127f9, __VMLINUX_SYMBOL_STR(rdma_destroy_id) },
	{ 0x3e3bcce9, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x21907cfa, __VMLINUX_SYMBOL_STR(ib_free_cq) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x2dd78a03, __VMLINUX_SYMBOL_STR(blk_mq_complete_request) },
	{ 0xe1b02d13, __VMLINUX_SYMBOL_STR(nvmf_reg_write32) },
	{ 0xe5840ec6, __VMLINUX_SYMBOL_STR(ib_wc_status_msg) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x72e0f62a, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0xdd87eb28, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x808b316e, __VMLINUX_SYMBOL_STR(ib_alloc_mr) },
	{ 0x4549823e, __VMLINUX_SYMBOL_STR(nvme_start_keep_alive) },
	{ 0x31c37f6e, __VMLINUX_SYMBOL_STR(nvme_enable_ctrl) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0xd0996e0f, __VMLINUX_SYMBOL_STR(nvme_io_timeout) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x4e41c19d, __VMLINUX_SYMBOL_STR(nvmf_connect_admin_queue) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x8fc52107, __VMLINUX_SYMBOL_STR(rdma_destroy_qp) },
	{ 0xe8a7948b, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0x92fbf025, __VMLINUX_SYMBOL_STR(nvme_init_identify) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x87fe3442, __VMLINUX_SYMBOL_STR(nvmf_reg_read64) },
	{ 0x5e91584c, __VMLINUX_SYMBOL_STR(nvmf_get_subsysnqn) },
	{ 0x6f630686, __VMLINUX_SYMBOL_STR(blk_mq_stop_hw_queues) },
	{ 0x327858b1, __VMLINUX_SYMBOL_STR(nvme_max_retries) },
	{ 0xb4dd86e9, __VMLINUX_SYMBOL_STR(nvme_requeue_req) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x826c54d1, __VMLINUX_SYMBOL_STR(nvme_queue_scan) },
	{ 0xb12c967d, __VMLINUX_SYMBOL_STR(nvme_put_ctrl) },
	{ 0xd0d20369, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x12d84c2d, __VMLINUX_SYMBOL_STR(blk_mq_start_stopped_hw_queues) },
	{ 0x2595b55e, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0xb4d81d05, __VMLINUX_SYMBOL_STR(ib_map_mr_sg) },
	{ 0xf46a47ed, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0xa677c872, __VMLINUX_SYMBOL_STR(nvme_init_ctrl) },
	{ 0x9176a200, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x797869a7, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0x97d32f33, __VMLINUX_SYMBOL_STR(nvme_change_ctrl_state) },
	{ 0x45b1ca34, __VMLINUX_SYMBOL_STR(nvmf_unregister_transport) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xaccabc6a, __VMLINUX_SYMBOL_STR(in4_pton) },
	{ 0x39aef50c, __VMLINUX_SYMBOL_STR(nvme_cancel_request) },
	{ 0xcef51982, __VMLINUX_SYMBOL_STR(kstrtou16) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xc46ec7e, __VMLINUX_SYMBOL_STR(nvmf_get_address) },
	{ 0xc9e23d4f, __VMLINUX_SYMBOL_STR(blk_rq_map_sg) },
	{ 0x54aa5818, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0x6c87dbc9, __VMLINUX_SYMBOL_STR(blk_mq_reinit_tagset) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xf6b41035, __VMLINUX_SYMBOL_STR(rdma_disconnect) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1e13f75c, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0xf0d5bc06, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0xdbc469a4, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0x650273ac, __VMLINUX_SYMBOL_STR(nvmf_reg_read32) },
	{ 0x9d6e9700, __VMLINUX_SYMBOL_STR(sg_free_table_chained) },
	{ 0xdb73ec62, __VMLINUX_SYMBOL_STR(nvme_queue_async_events) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe3531f3a, __VMLINUX_SYMBOL_STR(nvmf_connect_io_queue) },
	{ 0x806aeee0, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0x38262da4, __VMLINUX_SYMBOL_STR(nvme_setup_cmd) },
	{ 0xb56c2782, __VMLINUX_SYMBOL_STR(nvme_stop_keep_alive) },
	{ 0xf958ab24, __VMLINUX_SYMBOL_STR(admin_timeout) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x7512ed9, __VMLINUX_SYMBOL_STR(__ib_alloc_pd) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x45905832, __VMLINUX_SYMBOL_STR(nvme_start_queues) },
	{ 0xffd4fca3, __VMLINUX_SYMBOL_STR(nvmf_free_options) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x907df803, __VMLINUX_SYMBOL_STR(rdma_event_msg) },
	{ 0xe350c0a8, __VMLINUX_SYMBOL_STR(nvme_uninit_ctrl) },
	{ 0xcee37b39, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xf1d07104, __VMLINUX_SYMBOL_STR(ib_alloc_cq) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_core,nvme-fabrics,nvme-core,rdma_cm";

