#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6cc42aee, __VMLINUX_SYMBOL_STR(proc_dointvec_minmax) },
	{ 0x36e3c4d4, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x402b8281, __VMLINUX_SYMBOL_STR(__request_module) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc897c382, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0x4b58ab18, __VMLINUX_SYMBOL_STR(xprt_lookup_rqst) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x686bf4c0, __VMLINUX_SYMBOL_STR(register_sysctl_table) },
	{ 0x7f1ac199, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x207e208d, __VMLINUX_SYMBOL_STR(ib_drain_qp) },
	{ 0xfc3d0904, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x8507c383, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0x4a6a5512, __VMLINUX_SYMBOL_STR(svc_xprt_enqueue) },
	{ 0x9624c285, __VMLINUX_SYMBOL_STR(svc_reg_xprt_class) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x62332b12, __VMLINUX_SYMBOL_STR(xprt_register_transport) },
	{ 0x89ed80d1, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xa00259e9, __VMLINUX_SYMBOL_STR(rdma_accept) },
	{ 0xaf2c529, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xa1374974, __VMLINUX_SYMBOL_STR(put_zone_device_page) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xdd85c56d, __VMLINUX_SYMBOL_STR(xprt_free) },
	{ 0xd99127f9, __VMLINUX_SYMBOL_STR(rdma_destroy_id) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x21907cfa, __VMLINUX_SYMBOL_STR(ib_free_cq) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x9190e705, __VMLINUX_SYMBOL_STR(xprt_alloc) },
	{ 0xee227fe, __VMLINUX_SYMBOL_STR(rpcb_getport_async) },
	{ 0xd22fdbfa, __VMLINUX_SYMBOL_STR(xprt_wake_pending_tasks) },
	{ 0xe5840ec6, __VMLINUX_SYMBOL_STR(ib_wc_status_msg) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xd14b3db0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x72e0f62a, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0x16ac1ca6, __VMLINUX_SYMBOL_STR(svc_unreg_xprt_class) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x31a89d59, __VMLINUX_SYMBOL_STR(rpc_debug) },
	{ 0x1e491a04, __VMLINUX_SYMBOL_STR(ib_unmap_fmr) },
	{ 0x808b316e, __VMLINUX_SYMBOL_STR(ib_alloc_mr) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xaf2b77e0, __VMLINUX_SYMBOL_STR(svc_xprt_init) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x8fc52107, __VMLINUX_SYMBOL_STR(rdma_destroy_qp) },
	{ 0xb23ce60e, __VMLINUX_SYMBOL_STR(rdma_listen) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x3e1788b6, __VMLINUX_SYMBOL_STR(xprt_unregister_transport) },
	{ 0xf1bb9c15, __VMLINUX_SYMBOL_STR(rdma_set_afonly) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xe413b06d, __VMLINUX_SYMBOL_STR(svc_xprt_copy_addrs) },
	{ 0xd05bae31, __VMLINUX_SYMBOL_STR(xprt_release_xprt_cong) },
	{ 0xd0d20369, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x2595b55e, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0xb4d81d05, __VMLINUX_SYMBOL_STR(ib_map_mr_sg) },
	{ 0xf46a47ed, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0x9cab0fe, __VMLINUX_SYMBOL_STR(svc_xprt_put) },
	{ 0xc4643a2c, __VMLINUX_SYMBOL_STR(rdma_bind_addr) },
	{ 0x37dfba41, __VMLINUX_SYMBOL_STR(svc_create_xprt) },
	{ 0x3e046816, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x797869a7, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0xafa3fbbc, __VMLINUX_SYMBOL_STR(ib_dealloc_fmr) },
	{ 0x3ba8aab2, __VMLINUX_SYMBOL_STR(xprt_alloc_slot) },
	{ 0x3f4716c8, __VMLINUX_SYMBOL_STR(unregister_sysctl_table) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0x231efe84, __VMLINUX_SYMBOL_STR(flush_delayed_work) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0x8489f699, __VMLINUX_SYMBOL_STR(xprt_put) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xf6b41035, __VMLINUX_SYMBOL_STR(rdma_disconnect) },
	{ 0x1e418471, __VMLINUX_SYMBOL_STR(ib_alloc_fmr) },
	{ 0xa1a0d8aa, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x6fcc7d5c, __VMLINUX_SYMBOL_STR(ib_query_qp) },
	{ 0xdbc469a4, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0xdc21b5ac, __VMLINUX_SYMBOL_STR(xprt_complete_rqst) },
	{ 0xf6ed3334, __VMLINUX_SYMBOL_STR(ib_event_msg) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1f2a9970, __VMLINUX_SYMBOL_STR(rpc_ntop) },
	{ 0xd8b5e860, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xe080d01f, __VMLINUX_SYMBOL_STR(xprt_set_retrans_timeout_def) },
	{ 0x15ab3c24, __VMLINUX_SYMBOL_STR(xprt_get) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x55e60e19, __VMLINUX_SYMBOL_STR(xprt_reserve_xprt_cong) },
	{ 0x806aeee0, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x7512ed9, __VMLINUX_SYMBOL_STR(__ib_alloc_pd) },
	{ 0x1be8ea8c, __VMLINUX_SYMBOL_STR(xprt_disconnect_done) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x3b4da9da, __VMLINUX_SYMBOL_STR(xprt_release_rqst_cong) },
	{ 0x907df803, __VMLINUX_SYMBOL_STR(rdma_event_msg) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0xce104fcc, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x3f0f863f, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xf1d07104, __VMLINUX_SYMBOL_STR(ib_alloc_cq) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=sunrpc,ib_core,rdma_cm";

