#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe019328a, __VMLINUX_SYMBOL_STR(rpcauth_register) },
	{ 0x1023fc66, __VMLINUX_SYMBOL_STR(xdr_shift_buf) },
	{ 0x36e3c4d4, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xac38b899, __VMLINUX_SYMBOL_STR(auth_domain_put) },
	{ 0x402b8281, __VMLINUX_SYMBOL_STR(__request_module) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xa58a8840, __VMLINUX_SYMBOL_STR(rpc_destroy_wait_queue) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x4ee7a780, __VMLINUX_SYMBOL_STR(sunrpc_cache_update) },
	{ 0x79ee49, __VMLINUX_SYMBOL_STR(xdr_buf_read_netobj) },
	{ 0x821a4513, __VMLINUX_SYMBOL_STR(xdr_init_encode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2825a945, __VMLINUX_SYMBOL_STR(rpc_init_pipe_dir_object) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x50d5f904, __VMLINUX_SYMBOL_STR(cache_destroy_net) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x779a18af, __VMLINUX_SYMBOL_STR(kstrtoll) },
	{ 0xb5b089fd, __VMLINUX_SYMBOL_STR(rpcauth_init_cred) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x8df842d1, __VMLINUX_SYMBOL_STR(rpc_unlink) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x24a6b8f9, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x40be126a, __VMLINUX_SYMBOL_STR(rpcauth_generic_bind_cred) },
	{ 0x465fda1, __VMLINUX_SYMBOL_STR(rpc_init_wait_queue) },
	{ 0xf668ba9, __VMLINUX_SYMBOL_STR(svc_auth_unregister) },
	{ 0xf84214f4, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0xe8fcbee7, __VMLINUX_SYMBOL_STR(xdr_inline_pages) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xf05afa33, __VMLINUX_SYMBOL_STR(cache_register_net) },
	{ 0x643d9ba1, __VMLINUX_SYMBOL_STR(groups_free) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0xc49a3d6f, __VMLINUX_SYMBOL_STR(gssd_running) },
	{ 0x75d846a6, __VMLINUX_SYMBOL_STR(rpc_mkpipe_data) },
	{ 0xb10a4d2e, __VMLINUX_SYMBOL_STR(rpc_mkpipe_dentry) },
	{ 0xaec14692, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xea6d7008, __VMLINUX_SYMBOL_STR(nonseekable_open) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x6daf086d, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x979206f5, __VMLINUX_SYMBOL_STR(rpc_remove_pipe_dir_object) },
	{ 0x9878745c, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x8efc766e, __VMLINUX_SYMBOL_STR(xdr_buf_subsegment) },
	{ 0x5f0ceb8, __VMLINUX_SYMBOL_STR(svcauth_unix_set_client) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x6564c0d1, __VMLINUX_SYMBOL_STR(PDE_DATA) },
	{ 0x31a89d59, __VMLINUX_SYMBOL_STR(rpc_debug) },
	{ 0x445a4d2c, __VMLINUX_SYMBOL_STR(cache_check) },
	{ 0x3c80c06c, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x75a4673c, __VMLINUX_SYMBOL_STR(rpc_queue_upcall) },
	{ 0xedbb6d30, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x7da83a10, __VMLINUX_SYMBOL_STR(rpc_call_sync) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xc4f01d9a, __VMLINUX_SYMBOL_STR(rpc_create) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xaf37f4b3, __VMLINUX_SYMBOL_STR(sunrpc_cache_lookup) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6e9d036d, __VMLINUX_SYMBOL_STR(rpc_call_null) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xf989ff22, __VMLINUX_SYMBOL_STR(xdr_init_decode) },
	{ 0xf408a8b2, __VMLINUX_SYMBOL_STR(rpcauth_init_credcache) },
	{ 0xe97f4ce5, __VMLINUX_SYMBOL_STR(qword_get) },
	{ 0xc8e96dea, __VMLINUX_SYMBOL_STR(qword_addhex) },
	{ 0x7719922a, __VMLINUX_SYMBOL_STR(rpcauth_lookup_credcache) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0xaf6ae696, __VMLINUX_SYMBOL_STR(kstrndup) },
	{ 0x9d91f28f, __VMLINUX_SYMBOL_STR(cache_unregister_net) },
	{ 0x3e046816, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x2f456f2d, __VMLINUX_SYMBOL_STR(rpc_pipe_generic_upcall) },
	{ 0xcde03c4b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xd0de6afa, __VMLINUX_SYMBOL_STR(rpc_destroy_pipe_data) },
	{ 0x9df6edca, __VMLINUX_SYMBOL_STR(svc_auth_register) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x2eec63c9, __VMLINUX_SYMBOL_STR(xdr_encode_netobj) },
	{ 0x16eaca25, __VMLINUX_SYMBOL_STR(rpc_wake_up_status) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x3998e097, __VMLINUX_SYMBOL_STR(auth_domain_lookup) },
	{ 0x4979c0c2, __VMLINUX_SYMBOL_STR(rpc_release_client) },
	{ 0x35a8afef, __VMLINUX_SYMBOL_STR(cache_purge) },
	{ 0xdca0af25, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x800fb92b, __VMLINUX_SYMBOL_STR(full_name_hash) },
	{ 0xa1a0d8aa, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0x28a3e7bc, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xa9167461, __VMLINUX_SYMBOL_STR(rpcauth_unregister) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x3e2b0ba6, __VMLINUX_SYMBOL_STR(groups_alloc) },
	{ 0xadde1e84, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0xe1ac2bb8, __VMLINUX_SYMBOL_STR(sunrpc_net_id) },
	{ 0xfc201b66, __VMLINUX_SYMBOL_STR(sprint_oid) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x3bb5114a, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x4ca9669f, __VMLINUX_SYMBOL_STR(scnprintf) },
	{ 0x37c3c34d, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x838662a8, __VMLINUX_SYMBOL_STR(read_bytes_from_xdr_buf) },
	{ 0xd600bf2b, __VMLINUX_SYMBOL_STR(rpc_net_ns) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0xb576eb37, __VMLINUX_SYMBOL_STR(rpcauth_destroy_credcache) },
	{ 0xd94bdb69, __VMLINUX_SYMBOL_STR(cache_create_net) },
	{ 0xf3ba48f1, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x3edd87da, __VMLINUX_SYMBOL_STR(auth_domain_find) },
	{ 0xf4308e79, __VMLINUX_SYMBOL_STR(rpc_shutdown_client) },
	{ 0xdbd64179, __VMLINUX_SYMBOL_STR(xdr_write_pages) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x4a492ac9, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x52d56a6b, __VMLINUX_SYMBOL_STR(xdr_set_scratch_buffer) },
	{ 0x14717dae, __VMLINUX_SYMBOL_STR(xdr_buf_from_iov) },
	{ 0x3c4f175f, __VMLINUX_SYMBOL_STR(rpc_find_or_alloc_pipe_dir_object) },
	{ 0xb548bff, __VMLINUX_SYMBOL_STR(xdr_buf_trim) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0x3f0f863f, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x1ebac2bd, __VMLINUX_SYMBOL_STR(getboottime64) },
	{ 0xe60fcd89, __VMLINUX_SYMBOL_STR(rpc_put_task) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=sunrpc,oid_registry";

