#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x14956723, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2fc111e, __VMLINUX_SYMBOL_STR(ata_std_prereset) },
	{ 0x8d9899c7, __VMLINUX_SYMBOL_STR(ata_port_wait_eh) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x4766e06d, __VMLINUX_SYMBOL_STR(scsi_change_queue_depth) },
	{ 0x67d00e7b, __VMLINUX_SYMBOL_STR(sas_remove_children) },
	{ 0xde4961e9, __VMLINUX_SYMBOL_STR(sas_release_transport) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb8eec98b, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0xa655ba58, __VMLINUX_SYMBOL_STR(blk_abort_request) },
	{ 0xe071e1bc, __VMLINUX_SYMBOL_STR(scsi_block_requests) },
	{ 0x572840ec, __VMLINUX_SYMBOL_STR(ata_std_sched_eh) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x77572204, __VMLINUX_SYMBOL_STR(sas_port_free) },
	{ 0xd4a29826, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0xb414cdbb, __VMLINUX_SYMBOL_STR(sas_phy_add) },
	{ 0xc1b2050d, __VMLINUX_SYMBOL_STR(scsi_unblock_requests) },
	{ 0xd7b25d07, __VMLINUX_SYMBOL_STR(ata_sas_slave_configure) },
	{ 0xb4023f1, __VMLINUX_SYMBOL_STR(ata_scsi_cmd_error_handler) },
	{ 0xf776916b, __VMLINUX_SYMBOL_STR(sas_port_add_phy) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xa7136deb, __VMLINUX_SYMBOL_STR(sas_rphy_free) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xf44d9bba, __VMLINUX_SYMBOL_STR(sas_port_delete_phy) },
	{ 0x16a72919, __VMLINUX_SYMBOL_STR(sas_rphy_add) },
	{ 0xe25e932, __VMLINUX_SYMBOL_STR(ata_sas_port_suspend) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x8af81cf1, __VMLINUX_SYMBOL_STR(ata_sas_port_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xd48c4c33, __VMLINUX_SYMBOL_STR(sas_port_delete) },
	{ 0x515dee7e, __VMLINUX_SYMBOL_STR(ata_sas_async_probe) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xb9f8311b, __VMLINUX_SYMBOL_STR(sas_attach_transport) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x6eed342d, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0x6542f2a4, __VMLINUX_SYMBOL_STR(sas_rphy_delete) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0xca003bd5, __VMLINUX_SYMBOL_STR(ata_sas_port_stop) },
	{ 0x602bb7ce, __VMLINUX_SYMBOL_STR(scsi_queue_work) },
	{ 0xeb1285bc, __VMLINUX_SYMBOL_STR(sas_expander_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x7448b37a, __VMLINUX_SYMBOL_STR(sas_read_port_mode_page) },
	{ 0x754535eb, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xe92da6b1, __VMLINUX_SYMBOL_STR(sas_end_device_alloc) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xc411afc3, __VMLINUX_SYMBOL_STR(ata_std_error_handler) },
	{ 0x49502b, __VMLINUX_SYMBOL_STR(ata_scsi_port_error_handler) },
	{ 0xd80de83, __VMLINUX_SYMBOL_STR(ata_sas_port_start) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x9e17defc, __VMLINUX_SYMBOL_STR(ata_std_qc_defer) },
	{ 0xf0113640, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x4e6db18f, __VMLINUX_SYMBOL_STR(sas_port_mark_backlink) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x5e3d935, __VMLINUX_SYMBOL_STR(sas_port_add) },
	{ 0x85825898, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0xf811e69d, __VMLINUX_SYMBOL_STR(scsi_eh_flush_done_q) },
	{ 0xae60e490, __VMLINUX_SYMBOL_STR(ata_port_schedule_eh) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x8d0fb03, __VMLINUX_SYMBOL_STR(ata_sas_port_alloc) },
	{ 0x39fc54ca, __VMLINUX_SYMBOL_STR(ata_noop_qc_prep) },
	{ 0x109e0357, __VMLINUX_SYMBOL_STR(scsi_eh_finish_cmd) },
	{ 0xd801a2d, __VMLINUX_SYMBOL_STR(sas_phy_free) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x82a27d45, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x73c832f2, __VMLINUX_SYMBOL_STR(ata_dev_classify) },
	{ 0x3e05bf46, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6cd21997, __VMLINUX_SYMBOL_STR(ata_tf_to_fis) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x37ecc9bd, __VMLINUX_SYMBOL_STR(sas_phy_alloc) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x23b5238a, __VMLINUX_SYMBOL_STR(ata_wait_after_reset) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x1e13f75c, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x1923c2c1, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xdc730ba0, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x26c90ea4, __VMLINUX_SYMBOL_STR(scsi_eh_get_sense) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x82701365, __VMLINUX_SYMBOL_STR(int_to_scsilun) },
	{ 0xb6244511, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xf204f4ce, __VMLINUX_SYMBOL_STR(ata_sas_port_resume) },
	{ 0xfbd06dbc, __VMLINUX_SYMBOL_STR(sas_port_get_phy) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0xf6cdc440, __VMLINUX_SYMBOL_STR(scsi_eh_ready_devs) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9304b6, __VMLINUX_SYMBOL_STR(ata_tf_from_fis) },
	{ 0x3bb5114a, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x6b8fe235, __VMLINUX_SYMBOL_STR(sas_port_alloc) },
	{ 0xcc0e9e9, __VMLINUX_SYMBOL_STR(ata_host_init) },
	{ 0xae9ac00d, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xcf600abd, __VMLINUX_SYMBOL_STR(scsi_schedule_eh) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xb34d83f5, __VMLINUX_SYMBOL_STR(ata_std_postreset) },
	{ 0x3fd734d9, __VMLINUX_SYMBOL_STR(sas_rphy_unlink) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xe1ce30d7, __VMLINUX_SYMBOL_STR(ata_sas_queuecmd) },
	{ 0x16eb9ec1, __VMLINUX_SYMBOL_STR(ata_sas_port_destroy) },
	{ 0xa38602cd, __VMLINUX_SYMBOL_STR(drain_workqueue) },
	{ 0x4b0d4d14, __VMLINUX_SYMBOL_STR(sas_rphy_remove) },
	{ 0xa4c8ef2b, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x9bc18408, __VMLINUX_SYMBOL_STR(ata_sas_scsi_ioctl) },
	{ 0xb3d7843e, __VMLINUX_SYMBOL_STR(__ata_change_queue_depth) },
	{ 0x69c05e10, __VMLINUX_SYMBOL_STR(ata_qc_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libata,scsi_mod,scsi_transport_sas";

