#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x42595e58, __VMLINUX_SYMBOL_STR(vgacon_text_force) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x3cb7fc58, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0xff7429e5, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x16f6da01, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6c67f3b3, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x8a15297e, __VMLINUX_SYMBOL_STR(ttm_dma_tt_init) },
	{ 0xbfcdb6b5, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0xae109b17, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0x6c344f8c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x374a0b88, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0xc0ac3cb7, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x2b6be8c1, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2bbe1764, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x5318c28c, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xe460f018, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0x52455f36, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_hw_done) },
	{ 0x4efb983c, __VMLINUX_SYMBOL_STR(drm_set_preferred_mode) },
	{ 0xe1f341c3, __VMLINUX_SYMBOL_STR(drm_atomic_helper_page_flip) },
	{ 0x465030fe, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x8828f38a, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0xb323a510, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0xfa64f844, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0x61cbcb49, __VMLINUX_SYMBOL_STR(virtio_check_driver_offered_feature) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1f087339, __VMLINUX_SYMBOL_STR(get_task_comm) },
	{ 0x4657ebaa, __VMLINUX_SYMBOL_STR(fence_context_alloc) },
	{ 0xfdf103f3, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xaf2c529, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0xccbfb029, __VMLINUX_SYMBOL_STR(fence_default_wait) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x591d2eba, __VMLINUX_SYMBOL_STR(drm_kms_helper_hotplug_event) },
	{ 0xe38f6d81, __VMLINUX_SYMBOL_STR(virtqueue_kick) },
	{ 0xf36c115f, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x5607bd80, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x780d34b9, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0x1653ba0b, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x69514955, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0x4ced8dab, __VMLINUX_SYMBOL_STR(virtqueue_get_buf) },
	{ 0xea92f995, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xd14b3db0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x4dcca53a, __VMLINUX_SYMBOL_STR(ttm_bo_default_swap_lru_tail) },
	{ 0xf90df965, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xc8f2246a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0xc008f94a, __VMLINUX_SYMBOL_STR(ttm_bo_default_lru_tail) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x1a6660eb, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x6510f010, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0x1f570e83, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x988aab98, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0xe8f691cf, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xbb7294d5, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0xe81ef1dd, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0x14f38446, __VMLINUX_SYMBOL_STR(virtqueue_add_sgs) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xaae2fc90, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0x754535eb, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xf56d9856, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0x50dd809e, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xb2a07f0a, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0xe8465922, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xbcda5cc6, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x7fc7f551, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x5c5e5131, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x1f980e8d, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xdcdd2aec, __VMLINUX_SYMBOL_STR(virtqueue_disable_cb) },
	{ 0xcd08aa9, __VMLINUX_SYMBOL_STR(ttm_eu_fence_buffer_objects) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x84ffea8b, __VMLINUX_SYMBOL_STR(idr_preload) },
	{ 0x46963b5c, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x1a7fec9d, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x1c683eb, __VMLINUX_SYMBOL_STR(ttm_bo_dma_acc_size) },
	{ 0xc2115909, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x97e9b7b7, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x507cf82c, __VMLINUX_SYMBOL_STR(ttm_bo_wait) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0x6bf514d5, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x85e7498f, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x6bfc959b, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x82fac0d, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0xdd1ec059, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x7e1966c0, __VMLINUX_SYMBOL_STR(fence_signal_locked) },
	{ 0xa02ac8bc, __VMLINUX_SYMBOL_STR(ttm_eu_backoff_reservation) },
	{ 0xe3312f97, __VMLINUX_SYMBOL_STR(virtqueue_get_vring_size) },
	{ 0x1823bdb9, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xf116b700, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x652fee6c, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0xde642d21, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0xe0fedb94, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0xd9355564, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_vblanks) },
	{ 0x16953875, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0xe4e2ab3a, __VMLINUX_SYMBOL_STR(unregister_virtio_driver) },
	{ 0x8d275ec5, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0x2017c10f, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0x1dc3e62b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x84e46f21, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xc6ab253e, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0x5243a3ac, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_disables) },
	{ 0x4cd777b1, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0xec568bf6, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xc402134e, __VMLINUX_SYMBOL_STR(drm_gem_handle_delete) },
	{ 0x111c7773, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xdcd769c0, __VMLINUX_SYMBOL_STR(ttm_eu_reserve_buffers) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x535b98f6, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x87cf2dab, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x9c296579, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0x292ea2c0, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x7b952d2e, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x6bb4acc0, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xe1790603, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xbf983fd8, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x52d6c6f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xe7f85de0, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_planes) },
	{ 0xb6244511, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xa9bd2676, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x93df10b1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0x81555a64, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x29ef53c3, __VMLINUX_SYMBOL_STR(ttm_dma_tt_fini) },
	{ 0x5e00e591, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa8cb44c4, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x7533cac4, __VMLINUX_SYMBOL_STR(drm_atomic_helper_cleanup_planes) },
	{ 0x7c0b324, __VMLINUX_SYMBOL_STR(sg_alloc_table_from_pages) },
	{ 0xeb4c4ccf, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xa71717b3, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xb1645a2e, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0xfa6d98e6, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0x3fc7f71, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0x9291cd3b, __VMLINUX_SYMBOL_STR(memdup_user) },
	{ 0x9793909e, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xc2245222, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0x843f4393, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x4201017, __VMLINUX_SYMBOL_STR(fence_init) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0xa5aa9f68, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0x3a0a92af, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x869854b8, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x777f7db0, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x49463637, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_enables) },
	{ 0xe3d6ba77, __VMLINUX_SYMBOL_STR(virtqueue_enable_cb) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0x7fde1c5c, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x2c6bcf20, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0xaf19932d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x80dcd3df, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0xfa8d3fb6, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x77667d8b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
	{ 0xd015836a, __VMLINUX_SYMBOL_STR(register_virtio_driver) },
	{ 0xeef21dc3, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xfcfd7c4, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,ttm,virtio,virtio_ring";

MODULE_ALIAS("virtio:d00000010v*");
