#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x42595e58, __VMLINUX_SYMBOL_STR(vgacon_text_force) },
	{ 0xff7429e5, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x16f6da01, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6c67f3b3, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x5e25804, __VMLINUX_SYMBOL_STR(__request_region) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x794357e6, __VMLINUX_SYMBOL_STR(ttm_tt_fini) },
	{ 0xb8a95c9e, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0xae109b17, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0xc0bdec99, __VMLINUX_SYMBOL_STR(drm_helper_resume_force_mode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x2b6be8c1, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x8c7e9ed3, __VMLINUX_SYMBOL_STR(arch_io_reserve_memtype_wc) },
	{ 0xc364ae22, __VMLINUX_SYMBOL_STR(iomem_resource) },
	{ 0x2bbe1764, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x44a602ce, __VMLINUX_SYMBOL_STR(drm_pci_exit) },
	{ 0x4efb983c, __VMLINUX_SYMBOL_STR(drm_set_preferred_mode) },
	{ 0x465030fe, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0xa9a8e17f, __VMLINUX_SYMBOL_STR(arch_phys_wc_add) },
	{ 0x8828f38a, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0xfdf103f3, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x5607bd80, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x69514955, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0xea92f995, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xd14b3db0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x4dcca53a, __VMLINUX_SYMBOL_STR(ttm_bo_default_swap_lru_tail) },
	{ 0xf90df965, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0xc008f94a, __VMLINUX_SYMBOL_STR(ttm_bo_default_lru_tail) },
	{ 0x1a6660eb, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x6510f010, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0xc6f32585, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x3f6e5c04, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_suspend) },
	{ 0x988aab98, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0xe8f691cf, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xbb7294d5, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0xe81ef1dd, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0xf10de535, __VMLINUX_SYMBOL_STR(ioread8) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xaae2fc90, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0x754535eb, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xf56d9856, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0x50dd809e, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xe8465922, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x7fc7f551, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x3d199a8f, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x5c5e5131, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x1f980e8d, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x6b23ab9f, __VMLINUX_SYMBOL_STR(ttm_tt_init) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x46963b5c, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x1c683eb, __VMLINUX_SYMBOL_STR(ttm_bo_dma_acc_size) },
	{ 0x97e9b7b7, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x6bf514d5, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x85e7498f, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x82fac0d, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x94431a74, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_enable) },
	{ 0xdd1ec059, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xf116b700, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x652fee6c, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0xafc4578, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x2017c10f, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x84e46f21, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0xc6ab253e, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0x727c4f3, __VMLINUX_SYMBOL_STR(iowrite8) },
	{ 0xb28b2bd1, __VMLINUX_SYMBOL_STR(ttm_bo_kunmap) },
	{ 0xd93f70f6, __VMLINUX_SYMBOL_STR(drm_get_pci_dev) },
	{ 0xec568bf6, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x111c7773, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x8d15114a, __VMLINUX_SYMBOL_STR(__release_region) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x535b98f6, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb2bd729c, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x9867dc7f, __VMLINUX_SYMBOL_STR(arch_io_free_memtype_wc) },
	{ 0x6bb4acc0, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xe1790603, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xbf983fd8, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x52d6c6f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x81555a64, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0xa8cb44c4, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0xa71717b3, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x3fc7f71, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0xe4da192e, __VMLINUX_SYMBOL_STR(ttm_bo_manager_func) },
	{ 0x5f07dfb1, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x50d68377, __VMLINUX_SYMBOL_STR(arch_phys_wc_del) },
	{ 0xc2245222, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xe2a58c67, __VMLINUX_SYMBOL_STR(drm_pci_init) },
	{ 0x843f4393, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x4c7924c8, __VMLINUX_SYMBOL_STR(drm_vma_node_is_allowed) },
	{ 0xa5aa9f68, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0x3a0a92af, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x869854b8, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x777f7db0, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x25af04cd, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x6073b011, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0xf52c311a, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0x2c6bcf20, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xaf19932d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x80dcd3df, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0xfa8d3fb6, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0xeef21dc3, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xfcfd7c4, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,ttm";

MODULE_ALIAS("pci:v00001013d000000B8sv00001AF4sd00001100bc*sc*i*");
MODULE_ALIAS("pci:v00001013d000000B8sv00005853sd00000001bc*sc*i*");
