#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xd5a98dd9, __VMLINUX_SYMBOL_STR(rdma_resolve_ip) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x78f02bdf, __VMLINUX_SYMBOL_STR(ib_send_cm_rej) },
	{ 0x7b492666, __VMLINUX_SYMBOL_STR(iw_cm_listen) },
	{ 0x72fa0438, __VMLINUX_SYMBOL_STR(ib_sa_classport_info_rec_query) },
	{ 0x237216fb, __VMLINUX_SYMBOL_STR(ib_attach_mcast) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb7e847f6, __VMLINUX_SYMBOL_STR(ib_query_gid) },
	{ 0xbc253a51, __VMLINUX_SYMBOL_STR(__fib_lookup) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xf4dcbc3b, __VMLINUX_SYMBOL_STR(rdma_port_get_link_layer) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x4a3c6f1d, __VMLINUX_SYMBOL_STR(roce_gid_type_mask_support) },
	{ 0x6e41ce6b, __VMLINUX_SYMBOL_STR(ib_sa_join_multicast) },
	{ 0x23ab5f9, __VMLINUX_SYMBOL_STR(ib_send_cm_req) },
	{ 0xb1c80c1c, __VMLINUX_SYMBOL_STR(ib_send_cm_dreq) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0xbbeaa943, __VMLINUX_SYMBOL_STR(ib_send_cm_rtu) },
	{ 0x5b56e022, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x5ad7a09f, __VMLINUX_SYMBOL_STR(iw_cm_init_qp_attr) },
	{ 0x89ed80d1, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x9816f2d0, __VMLINUX_SYMBOL_STR(ib_init_ah_from_path) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x75e2b96b, __VMLINUX_SYMBOL_STR(iw_cm_reject) },
	{ 0x8efb1ee3, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x4ab2e328, __VMLINUX_SYMBOL_STR(iw_cm_accept) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xaec14692, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0x317c3cc4, __VMLINUX_SYMBOL_STR(in_dev_finish_destroy) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0x872aee7c, __VMLINUX_SYMBOL_STR(ib_get_cached_gid) },
	{ 0xf7202784, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x7bb9ccbe, __VMLINUX_SYMBOL_STR(ib_send_cm_mra) },
	{ 0xf4b9b41b, __VMLINUX_SYMBOL_STR(ib_sa_free_multicast) },
	{ 0xda67efce, __VMLINUX_SYMBOL_STR(rdma_copy_addr) },
	{ 0xec0f42e, __VMLINUX_SYMBOL_STR(ib_get_net_dev_by_params) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfd60e15a, __VMLINUX_SYMBOL_STR(ib_create_qp) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x97091d4c, __VMLINUX_SYMBOL_STR(ib_send_cm_drep) },
	{ 0xc54e9a8c, __VMLINUX_SYMBOL_STR(ib_cm_init_qp_attr) },
	{ 0xedbb6d30, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x809388ca, __VMLINUX_SYMBOL_STR(idr_destroy) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x6a21c14c, __VMLINUX_SYMBOL_STR(__ethtool_get_link_ksettings) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x45e6a85c, __VMLINUX_SYMBOL_STR(iw_cm_disconnect) },
	{ 0xec3d8bdf, __VMLINUX_SYMBOL_STR(ibnl_put_attr) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x90e807c7, __VMLINUX_SYMBOL_STR(ib_cache_gid_parse_type_str) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x87a04cd1, __VMLINUX_SYMBOL_STR(ib_send_cm_rep) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x7be1a1af, __VMLINUX_SYMBOL_STR(ib_query_port) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x9c0d6b2e, __VMLINUX_SYMBOL_STR(iw_destroy_cm_id) },
	{ 0x414575a6, __VMLINUX_SYMBOL_STR(dev_get_by_index) },
	{ 0x95936806, __VMLINUX_SYMBOL_STR(config_group_init_type_name) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0x81da3dde, __VMLINUX_SYMBOL_STR(configfs_register_subsystem) },
	{ 0xb0fc8b65, __VMLINUX_SYMBOL_STR(ib_get_cached_pkey) },
	{ 0xd0d20369, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x7152ead5, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0x6daad3f4, __VMLINUX_SYMBOL_STR(ib_init_ah_from_mcmember) },
	{ 0x287d1e73, __VMLINUX_SYMBOL_STR(ib_sa_unregister_client) },
	{ 0x9571c946, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0x711cf8ec, __VMLINUX_SYMBOL_STR(ib_create_cm_id) },
	{ 0xad57bb9, __VMLINUX_SYMBOL_STR(ib_sa_path_rec_get) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x9176a200, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0xda0d50ec, __VMLINUX_SYMBOL_STR(ib_sa_cancel_query) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x93c8c71b, __VMLINUX_SYMBOL_STR(ib_sa_get_mcmember_rec) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0xef0983c5, __VMLINUX_SYMBOL_STR(ib_detach_mcast) },
	{ 0xb806af13, __VMLINUX_SYMBOL_STR(ib_cm_notify) },
	{ 0xd84578d7, __VMLINUX_SYMBOL_STR(rdma_addr_cancel) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xd34b4bd2, __VMLINUX_SYMBOL_STR(iw_cm_connect) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x1fbd16da, __VMLINUX_SYMBOL_STR(ip_tos2prio) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xdb96d9b3, __VMLINUX_SYMBOL_STR(ib_find_cached_pkey) },
	{ 0x8df3f3e7, __VMLINUX_SYMBOL_STR(ip_mc_inc_group) },
	{ 0xdca0af25, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x9d9cabc5, __VMLINUX_SYMBOL_STR(rdma_addr_register_client) },
	{ 0x606ec533, __VMLINUX_SYMBOL_STR(configfs_unregister_subsystem) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x1edc4064, __VMLINUX_SYMBOL_STR(rdma_addr_unregister_client) },
	{ 0x5611cdea, __VMLINUX_SYMBOL_STR(rdma_node_get_transport) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x8249aa3c, __VMLINUX_SYMBOL_STR(ib_destroy_cm_id) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xb6957a6c, __VMLINUX_SYMBOL_STR(ibnl_add_client) },
	{ 0x1c3c0ad3, __VMLINUX_SYMBOL_STR(rdma_addr_size) },
	{ 0xa9b5dd01, __VMLINUX_SYMBOL_STR(fib_table_lookup) },
	{ 0x8633a016, __VMLINUX_SYMBOL_STR(rdma_translate_ip) },
	{ 0x23f91ef7, __VMLINUX_SYMBOL_STR(rt6_lookup) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x5f51c4a, __VMLINUX_SYMBOL_STR(ib_sa_register_client) },
	{ 0xc67f14a5, __VMLINUX_SYMBOL_STR(ibnl_remove_client) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0x1f1419cf, __VMLINUX_SYMBOL_STR(ib_cm_insert_listen) },
	{ 0x27265267, __VMLINUX_SYMBOL_STR(ib_find_cached_gid_by_port) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x626ef722, __VMLINUX_SYMBOL_STR(ibnl_put_msg) },
	{ 0x84722b39, __VMLINUX_SYMBOL_STR(ip_mc_dec_group) },
	{ 0xa13864fe, __VMLINUX_SYMBOL_STR(config_group_init) },
	{ 0x4f0ff1c5, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_rep) },
	{ 0xcee37b39, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xa4dc42e6, __VMLINUX_SYMBOL_STR(inet_get_local_port_range) },
	{ 0xff6855bc, __VMLINUX_SYMBOL_STR(iw_create_cm_id) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x2a91bb33, __VMLINUX_SYMBOL_STR(ib_cache_gid_type_str) },
	{ 0x1fc5d6f7, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_req) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_core,ib_cm,iw_cm";

