#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x1bf77161, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0xdf74ed7e, __VMLINUX_SYMBOL_STR(sst_module_new) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x60118b25, __VMLINUX_SYMBOL_STR(sst_dsp_reset) },
	{ 0x2ed9019d, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0xba8c059e, __VMLINUX_SYMBOL_STR(sst_mem_block_register) },
	{ 0xcea7cc2a, __VMLINUX_SYMBOL_STR(sst_dsp_wake) },
	{ 0x35bed51a, __VMLINUX_SYMBOL_STR(snd_soc_unregister_platform) },
	{ 0x4a045773, __VMLINUX_SYMBOL_STR(sst_shim32_write) },
	{ 0xa08f28e8, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xd5eef67c, __VMLINUX_SYMBOL_STR(sst_dsp_get_offset) },
	{ 0x5e7f4920, __VMLINUX_SYMBOL_STR(snd_pcm_format_set_silence) },
	{ 0x8384062a, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0xbdb6d803, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x8e3dbd39, __VMLINUX_SYMBOL_STR(sst_dsp_shim_write) },
	{ 0x98058e4f, __VMLINUX_SYMBOL_STR(snd_dma_alloc_pages) },
	{ 0x1c68893, __VMLINUX_SYMBOL_STR(sst_module_get_from_id) },
	{ 0x9d8e8e29, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_read) },
	{ 0x24e99689, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0x9e2e40ac, __VMLINUX_SYMBOL_STR(sst_fw_new) },
	{ 0xdc47a235, __VMLINUX_SYMBOL_STR(sst_dsp_dma_get_channel) },
	{ 0x5c19ac8e, __VMLINUX_SYMBOL_STR(sst_dsp_dma_put_channel) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0xb12ccc1d, __VMLINUX_SYMBOL_STR(sst_memcpy_toio_32) },
	{ 0xd78aa6f1, __VMLINUX_SYMBOL_STR(sst_dsp_inbox_read) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x6f7596b, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x2a1314cc, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x9fb8a804, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_write) },
	{ 0x66ba2405, __VMLINUX_SYMBOL_STR(snd_soc_register_component) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x973f59aa, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits) },
	{ 0x223d5b81, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x4c59de79, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyfrom) },
	{ 0x57caaafe, __VMLINUX_SYMBOL_STR(snd_pcm_suspend_all) },
	{ 0xc7303bff, __VMLINUX_SYMBOL_STR(sst_ipc_tx_msg_reply_complete) },
	{ 0x1fef984, __VMLINUX_SYMBOL_STR(sst_ipc_reply_find_msg) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x1a10e569, __VMLINUX_SYMBOL_STR(sst_dsp_mailbox_init) },
	{ 0x57629b2e, __VMLINUX_SYMBOL_STR(sst_module_runtime_restore) },
	{ 0x8c4f27cf, __VMLINUX_SYMBOL_STR(sst_dsp_stall) },
	{ 0xafe8e77e, __VMLINUX_SYMBOL_STR(sst_module_runtime_new) },
	{ 0x1b5e8b82, __VMLINUX_SYMBOL_STR(sst_shim32_read) },
	{ 0xd64b2aec, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0x2434173e, __VMLINUX_SYMBOL_STR(snd_soc_poweroff) },
	{ 0x3dd12a0b, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xab65991, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyto) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x6c8bf41a, __VMLINUX_SYMBOL_STR(sst_dsp_sleep) },
	{ 0xe4b34b18, __VMLINUX_SYMBOL_STR(sst_ipc_init) },
	{ 0xf40e9158, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0x3bb0ea7a, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits_unlocked) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x996d50b6, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0xd95bf88b, __VMLINUX_SYMBOL_STR(sst_ipc_fini) },
	{ 0x735cbb74, __VMLINUX_SYMBOL_STR(sst_mem_block_unregister_all) },
	{ 0xef799d3b, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_tx) },
	{ 0xe05a21af, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0xbcec5387, __VMLINUX_SYMBOL_STR(sst_shim32_read64) },
	{ 0xd30ff080, __VMLINUX_SYMBOL_STR(snd_soc_unregister_component) },
	{ 0xee6dc507, __VMLINUX_SYMBOL_STR(perf_trace_run_bpf_submit) },
	{ 0xad5f0017, __VMLINUX_SYMBOL_STR(perf_trace_buf_alloc) },
	{ 0x312b3b2e, __VMLINUX_SYMBOL_STR(sst_dsp_shim_read_unlocked) },
	{ 0xaa6cf8e9, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_mono_info) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x945ee69d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0xe2cd795e, __VMLINUX_SYMBOL_STR(snd_soc_info_volsw) },
	{ 0xd9a2c94c, __VMLINUX_SYMBOL_STR(sst_shim32_write64) },
	{ 0x1e1555f9, __VMLINUX_SYMBOL_STR(arch_dma_alloc_attrs) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0x60d87982, __VMLINUX_SYMBOL_STR(sst_block_alloc_scratch) },
	{ 0x46f614fb, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_rx) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xdae2516e, __VMLINUX_SYMBOL_STR(kthread_queue_work) },
	{ 0x9a86f032, __VMLINUX_SYMBOL_STR(sst_module_runtime_alloc_blocks) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0x354b4b5b, __VMLINUX_SYMBOL_STR(sst_fw_reload) },
	{ 0x5cbe052f, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x2e4d11e8, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x3cf62e11, __VMLINUX_SYMBOL_STR(snd_soc_register_platform) },
	{ 0x7624f0ad, __VMLINUX_SYMBOL_STR(sst_fw_unload) },
	{ 0x6c7792e0, __VMLINUX_SYMBOL_STR(sst_module_alloc_blocks) },
	{ 0x8daf01ec, __VMLINUX_SYMBOL_STR(sst_module_free) },
	{ 0xa9d50ee, __VMLINUX_SYMBOL_STR(snd_dma_free_pages) },
	{ 0x5f19be6e, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_nowait) },
	{ 0x3861252f, __VMLINUX_SYMBOL_STR(snd_soc_suspend) },
	{ 0xdc909ca8, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x65f3676a, __VMLINUX_SYMBOL_STR(sst_module_runtime_save) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x1e13f75c, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x3f18b3c1, __VMLINUX_SYMBOL_STR(sst_ipc_drop_all) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x4dae5252, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0x4876de9d, __VMLINUX_SYMBOL_STR(sst_dsp_free) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x37835914, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0xce5a46f5, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x5a24e380, __VMLINUX_SYMBOL_STR(sst_memcpy_fromio_32) },
	{ 0x77617284, __VMLINUX_SYMBOL_STR(sst_fw_free_all) },
	{ 0x1f6696d5, __VMLINUX_SYMBOL_STR(sst_dsp_boot) },
	{ 0x28a8a713, __VMLINUX_SYMBOL_STR(sst_module_runtime_free) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0xae9ac00d, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xea7c17a, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0xc6d935da, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x6d63d4ff, __VMLINUX_SYMBOL_STR(snd_soc_resume) },
	{ 0x432dd47f, __VMLINUX_SYMBOL_STR(sst_module_runtime_get_from_id) },
	{ 0x8d32b478, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x11caddc7, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x31e30703, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_wait) },
	{ 0x2058d508, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xf98be831, __VMLINUX_SYMBOL_STR(sst_block_free_scratch) },
	{ 0x69738c24, __VMLINUX_SYMBOL_STR(snd_soc_bytes_info_ext) },
	{ 0xad5ec04c, __VMLINUX_SYMBOL_STR(sst_dsp_new) },
	{ 0x9807d25f, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0xa4c8ef2b, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x61bfbf1a, __VMLINUX_SYMBOL_STR(sst_module_runtime_free_blocks) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-soc-sst-firmware,snd-soc-sst-dsp,snd-soc-core,snd-pcm,snd-soc-sst-ipc,snd";

