#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xe0e56d14, __VMLINUX_SYMBOL_STR(neigh_lookup) },
	{ 0xc1586756, __VMLINUX_SYMBOL_STR(netdev_info) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xfa0c5c28, __VMLINUX_SYMBOL_STR(devlink_sb_unregister) },
	{ 0x71a153a0, __VMLINUX_SYMBOL_STR(skb_pad) },
	{ 0xf68285c0, __VMLINUX_SYMBOL_STR(register_inetaddr_notifier) },
	{ 0x9644b8cf, __VMLINUX_SYMBOL_STR(vlan_dev_vlan_id) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x754774f0, __VMLINUX_SYMBOL_STR(vlan_uses_dev) },
	{ 0x5762a0da, __VMLINUX_SYMBOL_STR(arp_tbl) },
	{ 0xc4dc0bf7, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_setlink) },
	{ 0x3699a24b, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_dump) },
	{ 0xb5ff38e0, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_set) },
	{ 0x57f7730a, __VMLINUX_SYMBOL_STR(netdev_has_any_upper_dev) },
	{ 0x1b66c649, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x2460c724, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0xbe4da188, __VMLINUX_SYMBOL_STR(netdev_all_lower_get_next) },
	{ 0xbfb7df3c, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_priv) },
	{ 0x39a96739, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_clear) },
	{ 0x23495edc, __VMLINUX_SYMBOL_STR(__dev_kfree_skb_any) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x6f6ebbe3, __VMLINUX_SYMBOL_STR(neigh_destroy) },
	{ 0xaec0d688, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_unregister) },
	{ 0xbf2b51fe, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_del) },
	{ 0x5a00da2b, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_getlink) },
	{ 0x2262cf77, __VMLINUX_SYMBOL_STR(skb_realloc_headroom) },
	{ 0xe2e47472, __VMLINUX_SYMBOL_STR(rhashtable_insert_slow) },
	{ 0xc7b461a, __VMLINUX_SYMBOL_STR(mlxsw_core_port_init) },
	{ 0x26a3d2e2, __VMLINUX_SYMBOL_STR(__neigh_create) },
	{ 0x9a19fdfd, __VMLINUX_SYMBOL_STR(netdev_all_lower_get_next_rcu) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0xe0729564, __VMLINUX_SYMBOL_STR(__dynamic_netdev_dbg) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xd9221413, __VMLINUX_SYMBOL_STR(__neigh_event_send) },
	{ 0xa2d8cfd7, __VMLINUX_SYMBOL_STR(rhashtable_destroy) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0x59c1d110, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0xdde2bdc4, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xc1a2a447, __VMLINUX_SYMBOL_STR(mlxsw_core_resources_get) },
	{ 0x479c3c86, __VMLINUX_SYMBOL_STR(find_next_zero_bit) },
	{ 0x709d2ebf, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0xfc3bba0f, __VMLINUX_SYMBOL_STR(unregister_fib_notifier) },
	{ 0xf38d4801, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0xe67fa7c3, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x4fe1eddf, __VMLINUX_SYMBOL_STR(unregister_netevent_notifier) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xd2c48dba, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0x668baa94, __VMLINUX_SYMBOL_STR(mlxsw_reg_trans_query) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xa453f9b0, __VMLINUX_SYMBOL_STR(mlxsw_core_rx_listener_register) },
	{ 0xd0d20369, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xcd526e29, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x9571c946, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0xbd671048, __VMLINUX_SYMBOL_STR(__alloc_percpu_gfp) },
	{ 0xec51e246, __VMLINUX_SYMBOL_STR(mlxsw_core_skb_transmit_busy) },
	{ 0x68ba66b, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_register) },
	{ 0xfe029963, __VMLINUX_SYMBOL_STR(unregister_inetaddr_notifier) },
	{ 0x147e01d4, __VMLINUX_SYMBOL_STR(mlxsw_core_port_fini) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xfdd89c3a, __VMLINUX_SYMBOL_STR(mlxsw_core_event_listener_register) },
	{ 0x36b9f401, __VMLINUX_SYMBOL_STR(eth_type_trans) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xcba9e5eb, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0xab0c687, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_get) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xbf49cd12, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_add) },
	{ 0x996c5d6d, __VMLINUX_SYMBOL_STR(mlxsw_reg_trans_bulk_wait) },
	{ 0xed433664, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x3247e4bb, __VMLINUX_SYMBOL_STR(mlxsw_core_schedule_dw) },
	{ 0xc57a4af4, __VMLINUX_SYMBOL_STR(rhashtable_init) },
	{ 0x6ef66e8a, __VMLINUX_SYMBOL_STR(_raw_read_lock_bh) },
	{ 0x31ec44a0, __VMLINUX_SYMBOL_STR(_raw_read_unlock_bh) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xc33a1010, __VMLINUX_SYMBOL_STR(devlink_sb_register) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x80822927, __VMLINUX_SYMBOL_STR(mlxsw_core_event_listener_unregister) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0x10b1ce71, __VMLINUX_SYMBOL_STR(mlxsw_core_rx_listener_unregister) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x6bacd73c, __VMLINUX_SYMBOL_STR(unregister_netdev) },
	{ 0xbbe897a7, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_dellink) },
	{ 0xdde7e8c0, __VMLINUX_SYMBOL_STR(mlxsw_reg_query) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x58003b01, __VMLINUX_SYMBOL_STR(register_fib_notifier) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0x4761f17c, __VMLINUX_SYMBOL_STR(register_netevent_notifier) },
	{ 0x6868ff1a, __VMLINUX_SYMBOL_STR(call_switchdev_notifiers) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x6250ca31, __VMLINUX_SYMBOL_STR(mlxsw_core_skb_transmit) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x3e0485e2, __VMLINUX_SYMBOL_STR(netdev_lower_get_next) },
	{ 0x59955b04, __VMLINUX_SYMBOL_STR(mlxsw_reg_write) },
	{ 0x68b47ff2, __VMLINUX_SYMBOL_STR(alloc_etherdev_mqs) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=devlink,mlxsw_core";

