#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xff7429e5, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x3147b479, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0x16f6da01, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xb8a95c9e, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0xbfcdb6b5, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0xae109b17, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0xfe911cbc, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xc0ac3cb7, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x2b6be8c1, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xaa3530c, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x2bbe1764, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x62c03f3d, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0xc97b7025, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0x80acdda4, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x43b76249, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0xb323a510, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x6dc0c9dc, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xfdf103f3, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x1546374a, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0x8aea0c4, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xf36c115f, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x119e2d4c, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x5607bd80, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xea92f995, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf90df965, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xa6a97585, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0xd759a2a6, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0x1a6660eb, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x50d1f870, __VMLINUX_SYMBOL_STR(pgprot_writecombine) },
	{ 0xc6f32585, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xe8f691cf, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xd3be2ffd, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0xe133c95e, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xf56d9856, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0x50dd809e, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x7fc7f551, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x3d199a8f, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x985ae93, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xd33da1cb, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x1f980e8d, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xa08a521a, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x46963b5c, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x1a7fec9d, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xc2115909, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x7fdb1180, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x85e7498f, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0xb4515daf, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0xc52400cb, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x82fac0d, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0xdd1ec059, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xce0a238e, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x2def69a, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x67052448, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0x5dd10eef, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x9c491f60, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x1823bdb9, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x258ff847, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xf116b700, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x652fee6c, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x14f9e09b, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x308bd681, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x7fc83b53, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0x5944d015, __VMLINUX_SYMBOL_STR(__cachemode2pte_tbl) },
	{ 0x56ed1576, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_export) },
	{ 0xafc4578, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x3e05bf46, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x84e46f21, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0xc6ab253e, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0x4cd777b1, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0xec568bf6, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x535b98f6, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xb2bd729c, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x5057cdbf, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0x292ea2c0, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x1923c2c1, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x7b952d2e, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x6bb4acc0, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xe1790603, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x1af1acca, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x7f8eb06e, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xb9fd3b1e, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0x52d6c6f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa9bd2676, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x81555a64, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x29b91655, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x2235af9, __VMLINUX_SYMBOL_STR(drm_fb_helper_deferred_io) },
	{ 0x8028f73e, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference) },
	{ 0x78e739aa, __VMLINUX_SYMBOL_STR(up) },
	{ 0x98bd8eb5, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0xa71717b3, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x4bfa4e63, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xb1645a2e, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x494e3393, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xaba57539, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x3fc7f71, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0xcc06bee5, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x5f07dfb1, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0xbd6a4fe3, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0xc2245222, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xa45560de, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x843f4393, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x2a16b584, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x3a0a92af, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x70b52d27, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x869854b8, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x777f7db0, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xc2e0ec20, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x6388591c, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0x6073b011, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0xf52c311a, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x7fde1c5c, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x2c6bcf20, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xaf19932d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x80dcd3df, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x33076644, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xfa8d3fb6, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xeef21dc3, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,usbcore";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");
