#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6bc3fbc0, __VMLINUX_SYMBOL_STR(__unregister_chrdev) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2689dbe0, __VMLINUX_SYMBOL_STR(drm_edid_get_monitor_name) },
	{ 0xb82bed63, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xa1bd967d, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0x41ebdaea, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0xe082d24a, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0xdedb6611, __VMLINUX_SYMBOL_STR(try_wait_for_completion) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0xdf033793, __VMLINUX_SYMBOL_STR(drm_atomic_nonblocking_commit) },
	{ 0x5a4e69f6, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x9b6e8a2a, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x278c030f, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0xaa50049e, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x162302d6, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x81188c30, __VMLINUX_SYMBOL_STR(match_string) },
	{ 0xc91787a6, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xc817bf36, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0xa1392f65, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0x5d364ecb, __VMLINUX_SYMBOL_STR(drm_property_create_blob) },
	{ 0x5318c28c, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xa0db93cf, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0x1d56d6ef, __VMLINUX_SYMBOL_STR(drm_bridge_attach) },
	{ 0x7af362b1, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0xd4c14632, __VMLINUX_SYMBOL_STR(system_unbound_wq) },
	{ 0xfc3d0904, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0x19ce2683, __VMLINUX_SYMBOL_STR(i2c_transfer) },
	{ 0x569e0723, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0xa0043546, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x64ea81d5, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xf349b760, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0xaf2c529, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x1d8fc50d, __VMLINUX_SYMBOL_STR(device_destroy) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x1c3a8aec, __VMLINUX_SYMBOL_STR(__register_chrdev) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0xc4c49367, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0x3e3bcce9, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xb9af88c, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0xf1e83d47, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x5607bd80, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x41ca5caa, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0x35224317, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0xe29e1d0e, __VMLINUX_SYMBOL_STR(out_of_line_wait_on_atomic_t) },
	{ 0xc16173ab, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x6064dbd1, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0x26948d96, __VMLINUX_SYMBOL_STR(copy_user_enhanced_fast_string) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x1653ba0b, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x23bae623, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xb7354081, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0xd14b3db0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x307751bb, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0xd370a3ca, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x8a0b12c6, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x68d31573, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0xa73501e1, __VMLINUX_SYMBOL_STR(drm_mode_object_reference) },
	{ 0x7cdd6065, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0x8cb389f8, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xe8f691cf, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x136348e8, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0xbad4db78, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0xcb68e34f, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0x7a05487e, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xf0d7bbbb, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xc05e355f, __VMLINUX_SYMBOL_STR(idr_alloc_cyclic) },
	{ 0x290b95d0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x394433a0, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0xeec4b548, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x7e4527c6, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3aed1793, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0xb2a07f0a, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6e30ba8e, __VMLINUX_SYMBOL_STR(drm_rect_rotate_inv) },
	{ 0xafb8c6ff, __VMLINUX_SYMBOL_STR(copy_user_generic_string) },
	{ 0x2e6d14a1, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0x2c7a154a, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0xa96eb277, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0x6130fde0, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0xc2c0edbe, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xf911df1f, __VMLINUX_SYMBOL_STR(fixed_size_llseek) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x6278722a, __VMLINUX_SYMBOL_STR(drm_bridge_detach) },
	{ 0xed7ad457, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0x498aff7a, __VMLINUX_SYMBOL_STR(device_create) },
	{ 0x7fdb1180, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x6d8a95e0, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0xa7ce0989, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x375886f, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x2def69a, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xf02c3222, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xd164b26e, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0x317e72d7, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0xbdcf8646, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0xe4b70088, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x72a98fdb, __VMLINUX_SYMBOL_STR(copy_user_generic_unrolled) },
	{ 0xff97f773, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0x158b68b7, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0xf8afd1a5, __VMLINUX_SYMBOL_STR(drm_dev_printk) },
	{ 0x69d1c8cd, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0xf50fea5, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x6c78af4f, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0xfef2c78f, __VMLINUX_SYMBOL_STR(idr_get_next) },
	{ 0x932ef199, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0x3221853a, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x40d04664, __VMLINUX_SYMBOL_STR(console_trylock) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xf4fded96, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x73bb6a00, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xb053adda, __VMLINUX_SYMBOL_STR(drm_rect_rotate) },
	{ 0x60c621fb, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0xa36925d7, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0xcc2d69fc, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xcbe19f2d, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0x70cc566f, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x111c7773, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x586b19e6, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xff150982, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0xf6e0144e, __VMLINUX_SYMBOL_STR(drm_crtc_commit_put) },
	{ 0x16b653fa, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0xe708ae1, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xe1790603, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x83358d05, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xb143e1d5, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x52d6c6f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0xc3c07ecf, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xe24fd3b5, __VMLINUX_SYMBOL_STR(class_destroy) },
	{ 0xae9ac00d, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x4bfa4e63, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x525a0058, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x378465f6, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0x893e4bb7, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x9793909e, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xcc06bee5, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x2f995b59, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0xef067a5e, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0x4ecda8e4, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x14e4201a, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0x2a565a25, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0x394fb6f, __VMLINUX_SYMBOL_STR(drm_mode_object_unreference) },
	{ 0x6c9ca28d, __VMLINUX_SYMBOL_STR(__class_create) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0xf52c311a, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xa4c8ef2b, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0x7c2d098f, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x12464601, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x64501505, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0x4611fcec, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";

