#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe56a9336, __VMLINUX_SYMBOL_STR(snd_pcm_format_width) },
	{ 0x55fae4ca, __VMLINUX_SYMBOL_STR(snd_soc_dapm_kcontrol_widget) },
	{ 0x977a7a93, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x54ef1a5e, __VMLINUX_SYMBOL_STR(pci_bus_read_config_byte) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc9846a4c, __VMLINUX_SYMBOL_STR(skl_put_pvt_id) },
	{ 0xb87999e4, __VMLINUX_SYMBOL_STR(snd_hdac_stream_start) },
	{ 0x9c1c2d13, __VMLINUX_SYMBOL_STR(skl_ipc_get_large_config) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2d62d364, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_cleanup) },
	{ 0xc120396c, __VMLINUX_SYMBOL_STR(snd_pcm_lib_default_mmap) },
	{ 0x35bed51a, __VMLINUX_SYMBOL_STR(snd_soc_unregister_platform) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x53ecf8ff, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_trigger) },
	{ 0x75f6fbd8, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_link) },
	{ 0xfe88c5ac, __VMLINUX_SYMBOL_STR(snd_soc_tplg_widget_bind_event) },
	{ 0x5ee83112, __VMLINUX_SYMBOL_STR(snd_hdac_i915_exit) },
	{ 0xc8e64fa6, __VMLINUX_SYMBOL_STR(snd_hdac_bus_alloc_stream_pages) },
	{ 0x8384062a, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0xbdb6d803, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x9f96a06b, __VMLINUX_SYMBOL_STR(snd_hdac_stream_reset) },
	{ 0x12723916, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_put) },
	{ 0x52232134, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync_trigger) },
	{ 0x3ecd2d52, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0x5fa743a7, __VMLINUX_SYMBOL_STR(snd_hdac_get_stream) },
	{ 0x3d69256, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_free_for_all) },
	{ 0x24e99689, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0xedffbd8e, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_set_stream_id) },
	{ 0xac0274cd, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_clear_stream_id) },
	{ 0x1173e267, __VMLINUX_SYMBOL_STR(skl_clear_module_cnt) },
	{ 0xc06661e4, __VMLINUX_SYMBOL_STR(snd_hdac_bus_handle_stream_irq) },
	{ 0xb728b7d, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_ml_capabilities) },
	{ 0x15d93988, __VMLINUX_SYMBOL_STR(pci_release_regions) },
	{ 0x7d93cca2, __VMLINUX_SYMBOL_STR(snd_hdac_stream_set_params) },
	{ 0xa9dcaab0, __VMLINUX_SYMBOL_STR(snd_hdac_stream_setup) },
	{ 0x651181, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x6f7596b, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x4320e18e, __VMLINUX_SYMBOL_STR(skl_ipc_set_large_config) },
	{ 0xd4825f5d, __VMLINUX_SYMBOL_STR(pm_runtime_allow) },
	{ 0x3b0809ea, __VMLINUX_SYMBOL_STR(snd_hdac_bus_parse_capabilities) },
	{ 0x66ba2405, __VMLINUX_SYMBOL_STR(snd_soc_register_component) },
	{ 0x76b22d7f, __VMLINUX_SYMBOL_STR(skl_ipc_delete_pipeline) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0xec4df693, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_integer) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x6ca9fc98, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_spib) },
	{ 0xce2840e7, __VMLINUX_SYMBOL_STR(irq_set_irq_wake) },
	{ 0x1a03bd74, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_cmd_io) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xd4a74794, __VMLINUX_SYMBOL_STR(pci_set_master) },
	{ 0x15ab3929, __VMLINUX_SYMBOL_STR(snd_hdac_display_power) },
	{ 0x3dd12a0b, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xd1805152, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x8fd50eef, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x307ef8b3, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync) },
	{ 0x43d97d3e, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_cmd_io) },
	{ 0xed5483bf, __VMLINUX_SYMBOL_STR(snd_soc_tplg_component_load) },
	{ 0xa47bef41, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_reset) },
	{ 0x4ed20969, __VMLINUX_SYMBOL_STR(sst_acpi_find_machine) },
	{ 0xfeac0551, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_spbcap_enable) },
	{ 0x7cebd20f, __VMLINUX_SYMBOL_STR(platform_device_alloc) },
	{ 0x57d248a2, __VMLINUX_SYMBOL_STR(skl_get_pvt_instance_id_map) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xe942b025, __VMLINUX_SYMBOL_STR(platform_device_add) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x9e9fdd9d, __VMLINUX_SYMBOL_STR(memunmap) },
	{ 0x5e706ecf, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_init_all) },
	{ 0x90116914, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_lpib) },
	{ 0x5ec06e10, __VMLINUX_SYMBOL_STR(pci_bus_write_config_dword) },
	{ 0xccb2a533, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x996d50b6, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0xaa562ade, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_release) },
	{ 0x96fb3eea, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_assign) },
	{ 0x71b163a4, __VMLINUX_SYMBOL_STR(skl_dsp_wake) },
	{ 0x6d8a95e0, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x2072ee9b, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0xe05a21af, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0xd30ff080, __VMLINUX_SYMBOL_STR(snd_soc_unregister_component) },
	{ 0xa5e75e9a, __VMLINUX_SYMBOL_STR(acpi_evaluate_dsm) },
	{ 0xdd9a804a, __VMLINUX_SYMBOL_STR(snd_hdac_calc_stream_format) },
	{ 0x945ee69d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0xf1b2d30, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_down) },
	{ 0x7b0ca806, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_dpibr) },
	{ 0xe523ad75, __VMLINUX_SYMBOL_STR(synchronize_irq) },
	{ 0xc542933a, __VMLINUX_SYMBOL_STR(timecounter_read) },
	{ 0xdd1dbdb, __VMLINUX_SYMBOL_STR(snd_hdac_stream_cleanup) },
	{ 0x2bfeb410, __VMLINUX_SYMBOL_STR(acpi_get_handle) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x8e5984e1, __VMLINUX_SYMBOL_STR(snd_hdac_stream_stop) },
	{ 0x9a6e8331, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_chip) },
	{ 0x830bd142, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x76519d74, __VMLINUX_SYMBOL_STR(snd_hdac_i915_init) },
	{ 0xe6124de5, __VMLINUX_SYMBOL_STR(snd_hdac_stream_free_all) },
	{ 0xaf99d5a9, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_drsm_enable) },
	{ 0xfcc06f73, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_decouple) },
	{ 0xa04897e, __VMLINUX_SYMBOL_STR(pci_bus_read_config_dword) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xb3bae92f, __VMLINUX_SYMBOL_STR(pci_intx) },
	{ 0x87d237fb, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_exit) },
	{ 0x83a78cc, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up_all) },
	{ 0x3cf62e11, __VMLINUX_SYMBOL_STR(snd_soc_register_platform) },
	{ 0x62a46ffe, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_prepare) },
	{ 0x8cfbbe12, __VMLINUX_SYMBOL_STR(snd_hdac_bus_free_stream_pages) },
	{ 0x211f68f1, __VMLINUX_SYMBOL_STR(getnstimeofday64) },
	{ 0xf2382ac3, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stop_streams) },
	{ 0xc9e1af7c, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_start) },
	{ 0x2d45137b, __VMLINUX_SYMBOL_STR(snd_hdac_stream_timecounter_init) },
	{ 0xb8ce303c, __VMLINUX_SYMBOL_STR(bxt_sst_init_fw) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xdc6dff4c, __VMLINUX_SYMBOL_STR(skl_dsp_sleep) },
	{ 0x3e16e9c4, __VMLINUX_SYMBOL_STR(skl_sst_dsp_cleanup) },
	{ 0x6853bb42, __VMLINUX_SYMBOL_STR(pci_unregister_driver) },
	{ 0x12dd745c, __VMLINUX_SYMBOL_STR(snd_pcm_set_sync) },
	{ 0x37db8cf1, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_int_enable) },
	{ 0x123f82f3, __VMLINUX_SYMBOL_STR(getrawmonotonic64) },
	{ 0x4e935eb4, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_device_remove) },
	{ 0xe582963d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xecbc1203, __VMLINUX_SYMBOL_STR(pci_ioremap_bar) },
	{ 0x1e13f75c, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x310f02ec, __VMLINUX_SYMBOL_STR(memremap) },
	{ 0xa0116503, __VMLINUX_SYMBOL_STR(skl_ipc_set_pipeline_state) },
	{ 0x7505fe, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_device_init) },
	{ 0x87558ae9, __VMLINUX_SYMBOL_STR(skl_ipc_create_pipeline) },
	{ 0x377719dd, __VMLINUX_SYMBOL_STR(skl_sst_init_fw) },
	{ 0x91673a02, __VMLINUX_SYMBOL_STR(snd_hdac_link_free_all) },
	{ 0xcceb9972, __VMLINUX_SYMBOL_STR(pci_bus_write_config_byte) },
	{ 0xc074e84e, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_setup) },
	{ 0xa086b377, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xc5bc79e0, __VMLINUX_SYMBOL_STR(skl_get_pvt_id) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xf4e863f8, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up) },
	{ 0x2a9835fd, __VMLINUX_SYMBOL_STR(pci_request_regions) },
	{ 0xb2f1ff96, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_chip) },
	{ 0xce5a46f5, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0x50060c55, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_minmax) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x5185e020, __VMLINUX_SYMBOL_STR(__pci_register_driver) },
	{ 0xae9ac00d, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x6ddd7747, __VMLINUX_SYMBOL_STR(snd_skl_get_module_info) },
	{ 0x6b11cebc, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_clear) },
	{ 0xea7c17a, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0x6159c618, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_enable) },
	{ 0x247c30a2, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x31b2bff, __VMLINUX_SYMBOL_STR(skl_ipc_init_instance) },
	{ 0x8e8a03e8, __VMLINUX_SYMBOL_STR(skl_ipc_bind_unbind) },
	{ 0xc6b3dc99, __VMLINUX_SYMBOL_STR(snd_hdac_bus_update_rirb) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xf1885cdb, __VMLINUX_SYMBOL_STR(snd_hdac_bus_get_response) },
	{ 0xbd9b1bb, __VMLINUX_SYMBOL_STR(snd_hdac_bus_enter_link_reset) },
	{ 0xd56b5f64, __VMLINUX_SYMBOL_STR(ktime_get_ts64) },
	{ 0xa724a88a, __VMLINUX_SYMBOL_STR(snd_hdac_bus_send_cmd) },
	{ 0x76f4ed74, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0x9807d25f, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x2f4939b6, __VMLINUX_SYMBOL_STR(bxt_sst_dsp_cleanup) },
	{ 0x6fbd1932, __VMLINUX_SYMBOL_STR(skl_sst_dsp_init) },
	{ 0xb5cc3228, __VMLINUX_SYMBOL_STR(bxt_sst_dsp_init) },
	{ 0xa4c8ef2b, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xb0aca7a3, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0x3f002745, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_down_all) },
	{ 0xe1abda02, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0x668e03a0, __VMLINUX_SYMBOL_STR(platform_device_put) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-pcm,snd-soc-core,snd-soc-skl-ipc,snd-hda-core,snd-hda-ext-core,snd-soc-sst-match";

MODULE_ALIAS("pci:v00008086d00009D70sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00005A98sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00009D71sv*sd*bc*sc*i*");
