#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0xb4c90cf6, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x66ba1246, __VMLINUX_SYMBOL_STR(__kfree_skb) },
	{ 0xa4f15159, __VMLINUX_SYMBOL_STR(dccp_v4_do_rcv) },
	{ 0x104bc4ee, __VMLINUX_SYMBOL_STR(inet6_csk_update_pmtu) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xac11c683, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x2583fa94, __VMLINUX_SYMBOL_STR(inet6_csk_bind_conflict) },
	{ 0x7da10652, __VMLINUX_SYMBOL_STR(ipv6_getsockopt) },
	{ 0x4403d421, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0xae647029, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0x2a897abb, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x19bbc157, __VMLINUX_SYMBOL_STR(inet6_add_protocol) },
	{ 0x881c888f, __VMLINUX_SYMBOL_STR(inet6_lookup_listener) },
	{ 0x1383be5f, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xdd33ac51, __VMLINUX_SYMBOL_STR(ipv6_opt_accepted) },
	{ 0x71bc2760, __VMLINUX_SYMBOL_STR(compat_ipv6_getsockopt) },
	{ 0x4afe73ed, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x4c8460bd, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0xa7bd1c8f, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xfaadd8dd, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x16309888, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x5b56e022, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x6bffb32, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0x651c61fb, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x81684a6a, __VMLINUX_SYMBOL_STR(dccp_req_err) },
	{ 0x79a5c95f, __VMLINUX_SYMBOL_STR(dccp_v4_conn_request) },
	{ 0x30213146, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x1abb134f, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0x4c3772a5, __VMLINUX_SYMBOL_STR(ipv6_dup_options) },
	{ 0xc40a3c81, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xcc559d99, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xc1eea8a1, __VMLINUX_SYMBOL_STR(inet6_release) },
	{ 0xb0d888b, __VMLINUX_SYMBOL_STR(icmpv6_err_convert) },
	{ 0xb2db284, __VMLINUX_SYMBOL_STR(inet6_register_protosw) },
	{ 0xda5bbad3, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0xee383733, __VMLINUX_SYMBOL_STR(ip6_xmit) },
	{ 0xfd2f1d7d, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0xe8c67705, __VMLINUX_SYMBOL_STR(inet6_getname) },
	{ 0xb98289ea, __VMLINUX_SYMBOL_STR(sock_rfree) },
	{ 0xd612c6d1, __VMLINUX_SYMBOL_STR(inet6_csk_xmit) },
	{ 0xc088974, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xb0b637a4, __VMLINUX_SYMBOL_STR(compat_sock_common_setsockopt) },
	{ 0xbe5dc4, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xd5aa09cf, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xb47cca30, __VMLINUX_SYMBOL_STR(csum_ipv6_magic) },
	{ 0xf8b8edbe, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0xc348b43c, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0x52d9e0fb, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xa4ca95cd, __VMLINUX_SYMBOL_STR(compat_sock_common_getsockopt) },
	{ 0xf3b81ea7, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0x28e73eb5, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x6f6c7d9e, __VMLINUX_SYMBOL_STR(ip6_dst_lookup_flow) },
	{ 0xedbb6d30, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0xf907ae87, __VMLINUX_SYMBOL_STR(__inet6_lookup_established) },
	{ 0x7d5d1d00, __VMLINUX_SYMBOL_STR(dccp_v4_request_recv_sock) },
	{ 0x8be7f646, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xabe19f93, __VMLINUX_SYMBOL_STR(compat_dccp_setsockopt) },
	{ 0xf8923fbb, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0xc6781b43, __VMLINUX_SYMBOL_STR(inet6_ioctl) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd1b73ffb, __VMLINUX_SYMBOL_STR(inet6_csk_route_req) },
	{ 0x3f3d2197, __VMLINUX_SYMBOL_STR(fl6_sock_lookup) },
	{ 0xffb74af4, __VMLINUX_SYMBOL_STR(fl6_update_dst) },
	{ 0xf0113640, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xdf27b83c, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0xcd4a100f, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xf4ff0dcf, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x79024b1b, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0xda4405c2, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x69699a3e, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0x7d7eecd6, __VMLINUX_SYMBOL_STR(inet6_hash_connect) },
	{ 0xfe3c8b03, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0xcfe3cb4, __VMLINUX_SYMBOL_STR(inet6_hash) },
	{ 0x44e7960e, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0xf8262ebd, __VMLINUX_SYMBOL_STR(sk_filter_trim_cap) },
	{ 0x973af667, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x49ffba98, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x96976ff7, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0xe20dd1e5, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x73b1d14d, __VMLINUX_SYMBOL_STR(__sk_receive_skb) },
	{ 0x685ec44a, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x980b1aae, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0x1cbc3d98, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x56a0e84d, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf5d16c3c, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0xe4fc4754, __VMLINUX_SYMBOL_STR(dccp_v4_send_check) },
	{ 0x640dcd8f, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x1a2e3b4c, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x8345fb3b, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0xd2fca388, __VMLINUX_SYMBOL_STR(dccp_invalid_packet) },
	{ 0x8e27d0ef, __VMLINUX_SYMBOL_STR(inet6_del_protocol) },
	{ 0x4219eac1, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0xdca0af25, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x27ad1769, __VMLINUX_SYMBOL_STR(dccp_syn_ack_timeout) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb45fd1c4, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0xa4ad071a, __VMLINUX_SYMBOL_STR(compat_dccp_getsockopt) },
	{ 0xaa9a3277, __VMLINUX_SYMBOL_STR(ipv6_setsockopt) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x8f8634f6, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0xe890d454, __VMLINUX_SYMBOL_STR(inet6_sk_rebuild_header) },
	{ 0x654ae439, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xda24b625, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x52462be4, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xfff83154, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0xe200f872, __VMLINUX_SYMBOL_STR(secure_dccpv6_sequence_number) },
	{ 0x47679a71, __VMLINUX_SYMBOL_STR(inet6_unregister_protosw) },
	{ 0x6336eccb, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x60d1bb89, __VMLINUX_SYMBOL_STR(inet6_bind) },
	{ 0xeff2804e, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x48ff646b, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x5a71fe84, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0xab414329, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x8ca3647e, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xc47bfbf5, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x7e7ee6bd, __VMLINUX_SYMBOL_STR(dccp_v4_connect) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xb2b97a6f, __VMLINUX_SYMBOL_STR(inet6_csk_addr2sockaddr) },
	{ 0x8b30bc14, __VMLINUX_SYMBOL_STR(compat_ipv6_setsockopt) },
	{ 0x3e3a89fc, __VMLINUX_SYMBOL_STR(inet6_destroy_sock) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp,dccp_ipv4";

