#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x67a4b66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb13e4705, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0xb4c90cf6, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x615261bd, __VMLINUX_SYMBOL_STR(__ip_route_output_key_hash) },
	{ 0xac11c683, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0xa8c83a9e, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x4403d421, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0xae647029, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0x2a897abb, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0xb1af6da0, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0x1383be5f, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xd899364a, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0x4afe73ed, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x4c8460bd, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0xa7bd1c8f, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xfaadd8dd, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x16309888, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x5b56e022, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x38708358, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0x651c61fb, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x30213146, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x1abb134f, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xc40a3c81, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xcc559d99, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xda5bbad3, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x4406b0fc, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0xfd2f1d7d, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc088974, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xb0b637a4, __VMLINUX_SYMBOL_STR(compat_sock_common_setsockopt) },
	{ 0xbe5dc4, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xd5aa09cf, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xf8b8edbe, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0xc348b43c, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xc32ed92, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x52d9e0fb, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xa4ca95cd, __VMLINUX_SYMBOL_STR(compat_sock_common_getsockopt) },
	{ 0xf3b81ea7, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0x28e73eb5, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0xcb751a35, __VMLINUX_SYMBOL_STR(compat_ip_getsockopt) },
	{ 0xedbb6d30, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x8be7f646, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xabe19f93, __VMLINUX_SYMBOL_STR(compat_dccp_setsockopt) },
	{ 0xf8923fbb, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x86d4f2d5, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0xdc1e3dfd, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xec5451b9, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0xf0113640, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x690c8387, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0xdf27b83c, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0xcd4a100f, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xf4ff0dcf, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x79024b1b, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0xd2eaf036, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0xda4405c2, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x69699a3e, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xfe3c8b03, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x44e7960e, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0xc9f41eda, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x973af667, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x49ffba98, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x96976ff7, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0xe20dd1e5, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x73b1d14d, __VMLINUX_SYMBOL_STR(__sk_receive_skb) },
	{ 0x67e45ca2, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0x685ec44a, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x980b1aae, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0x1cbc3d98, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x82e79af3, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x56a0e84d, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf5d16c3c, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0x640dcd8f, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x1a2e3b4c, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x8345fb3b, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x83fc488c, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0x4219eac1, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0xdca0af25, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x6345c45e, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x326b7b4a, __VMLINUX_SYMBOL_STR(compat_ip_setsockopt) },
	{ 0xb45fd1c4, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0xa4ad071a, __VMLINUX_SYMBOL_STR(compat_dccp_getsockopt) },
	{ 0x70c6ac5d, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x8f8634f6, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x654ae439, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0xcc0a765b, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xda24b625, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x52462be4, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0x1c7c0431, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0xfff83154, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0x6336eccb, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x1060e5d5, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0xeff2804e, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x48ff646b, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0xab414329, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x8ca3647e, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0xc47bfbf5, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0xa8903f9c, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0x26cf58ef, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x54590f86, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

